INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(423, 8, 39, 106, 2, 'Ramadan is a well behaved student', 'Average performance sit up promoted to ss2', NOW(), NOW()),
(424, 8, 39, 100, 8, 'Amira is a well behaved student', 'Very good performance promoted to ss2', NOW(), NOW()),
(359, 8, 39, 104, 4, 'She is friendly and ready to learn', 'Average performance. Sit up', NOW(), NOW()),
(425, 8, 39, 96, 12, 'Firdausi is a well behaved student', 'Good performance promoted to ss2', NOW(), NOW()),
(426, 8, 39, 100, 8, 'Ademola is quiet in class', 'Fair results sit up promoted to ss2', NOW(), NOW()),
(427, 8, 39, 106, 2, 'Yusuf is very quiet in the class', 'Fair results sit up promoted to ss2', NOW(), NOW()),
(428, 8, 39, 102, 6, 'Abideen is too playful in the class', 'Poor result promoted on trial to ss2', NOW(), NOW()),
(429, 8, 39, 96, 12, 'Mohammad should get serious with his studies', 'Poor result sit up', NOW(), NOW()),
(430, 8, 39, 62, 46, 'Success is never serious with his academics', 'Fail', NOW(), NOW()),
(436, 8, 39, 108, 0, 'Well behaved student', 'Good results promoted to ss3', NOW(), NOW()),
(439, 8, 39, 102, 6, 'Well behaved student', 'Average performance promoted to ss3', NOW(), NOW()),
(440, 8, 39, 104, 4, 'Well behaved student', 'Good results promoted to ss3', NOW(), NOW()),
(441, 8, 39, 100, 8, 'Well behaved student', 'Average performance promoted to ss3', NOW(), NOW()),
(442, 8, 39, 104, 4, 'Well behaved student', 'Good performance keep it up promoted to ss3', NOW(), NOW()),
(443, 8, 39, 104, 4, 'Well behaved student', 'Average performance promoted to ss3', NOW(), NOW()),
(445, 8, 39, 106, 2, 'Well behaved student', 'Fair results sit up promoted to ss3', NOW(), NOW()),
(447, 8, 39, 0, 0, '', 'Good results promoted to ss3', NOW(), NOW()),
(360, 8, 39, 108, 0, 'He is focused and always ready to learn', 'A very good result. Keep it up.', NOW(), NOW()),
(362, 8, 39, 100, 8, 'He is ready to learn and inquisitive in class', 'Good result. Keep it up.', NOW(), NOW()),
(363, 8, 39, 108, 0, 'She is friendly but has a lazy attitude towards her class activities', 'Fair attempt. Try harder.', NOW(), NOW()),
(364, 8, 39, 0, 0, '', 'Very good result. Keep it up.', NOW(), NOW()),
(328, 9, 25, 124, 2, 'She takes an active role in discussion', 'Waoo this is excellent result keep it', NOW(), NOW()),
(436, 9, 25, 122, 4, 'Yetunde is well behaved and serious with her study', 'Good academic report. Well done!', NOW(), NOW()),
(440, 9, 25, 116, 10, 'A good performance work harder', 'Above average performance.  Do not relent.', NOW(), NOW()),
(441, 9, 25, 122, 4, 'An average performance improve more on it', 'Fair attempt.  Sit up!', NOW(), NOW()),
(442, 9, 25, 122, 4, 'A good performance keep it up', 'Good academic report.  Do not relent.', NOW(), NOW()),
(443, 9, 25, 110, 16, 'Abubakar need to concentrate more on his studies', 'Fair attempt. You have the ability to do better than this. Yes, I believe in you dear.', NOW(), NOW()),
(445, 9, 25, 122, 4, 'Below average performance work harder for a better result', 'Poor attempt.  You can surpass this performance if you put more effort.', NOW(), NOW()),
(326, 9, 25, 126, 0, 'Sheâ€™s a good girl and well mannered.', 'Excellent result keep it', NOW(), NOW()),
(327, 9, 25, 126, 0, 'Sheâ€™s a good girl and well behaved', 'Good results try harder next term', NOW(), NOW()),
(330, 9, 25, 126, 0, 'Sheâ€™s so brilliant and well behaved', 'Excellent result keep it up', NOW(), NOW()),
(331, 9, 25, 126, 0, 'Heâ€™s a good boy', 'Poor performance sit up to the school standard', NOW(), NOW()),
(338, 9, 25, 126, 0, 'She is showing impressive growth', 'Very impressed performance try harder next term', NOW(), NOW()),
(339, 9, 25, 122, 4, 'So brilliant and well preserved', 'Excellent result keep it up', NOW(), NOW()),
(349, 9, 25, 126, 0, 'You consistently show respect to your teachers and peers', 'Excellent result keep it up', NOW(), NOW()),
(340, 9, 25, 126, 0, 'Sheâ€™s a good girl and well behaved', 'Average performance sit up', NOW(), NOW()),
(341, 9, 25, 124, 2, 'Sheâ€™s a good girl and well behaved', 'Very good performance keep it up', NOW(), NOW()),
(342, 9, 25, 122, 4, 'Sheâ€™s calm and well behaved', 'Average performance try harder next term', NOW(), NOW()),
(329, 9, 25, 124, 2, 'She takes an active role in class', 'Average performance try harder next term', NOW(), NOW()),
(354, 9, 25, 122, 4, 'Heâ€™s always active and ready to learn more', 'Good performance keep it up', NOW(), NOW()),
(336, 9, 25, 124, 2, 'You are gradually improving.', 'Good performance you can do more than this', NOW(), NOW()),
(343, 9, 25, 124, 2, 'Your commitment to academics is commendable but more humility is required', '', NOW(), NOW()),
(334, 9, 25, 108, 18, 'She is very gentle and quiet.', 'Very poor result sit up', NOW(), NOW()),
(335, 9, 25, 124, 2, 'Please be more serious', 'Fair results sit up', NOW(), NOW()),
(356, 9, 25, 118, 8, 'Sheâ€™s a good girl and well behaved', 'Good results', NOW(), NOW()),
(357, 9, 25, 116, 10, 'Sheâ€™s good and calm', 'Fair results be serious with your academics', NOW(), NOW()),
(358, 9, 25, 110, 16, 'Heâ€™s a good boy', 'Fair results sit up', NOW(), NOW()),
(333, 9, 25, 124, 2, 'She takes an active part in the class', 'Good performance keep it up', NOW(), NOW()),
(359, 9, 25, 116, 10, 'Funmilayo is always ready to improve for the better.', 'Average performance try harder next term', NOW(), NOW()),
(360, 9, 25, 112, 14, 'Heâ€™s a good boy', 'Average performance sit up', NOW(), NOW()),
(361, 9, 25, 124, 2, 'Heâ€™s always active and ready to learn more', 'Average performance try harder next term', NOW(), NOW()),
(351, 9, 25, 118, 8, 'If you settle down to study you can still achieve alot', 'Good performance you can do better than this next term', NOW(), NOW()),
(350, 9, 25, 108, 18, 'He is always paying attention in class and very neat', 'Good performance keep it up', NOW(), NOW()),
(362, 9, 25, 124, 2, 'Heâ€™s a good boy', 'Average performance try harder next term', NOW(), NOW()),
(348, 9, 25, 104, 22, 'Try to work harder', 'Fair performance try harder next term', NOW(), NOW()),
(364, 9, 25, 122, 4, 'Very smart and intelligent', 'Excellent performance keep it', NOW(), NOW()),
(366, 9, 25, 122, 4, 'Heâ€™s a good boy ,but he need to buckle up academically', 'Poor result sit up', NOW(), NOW()),
(367, 9, 25, 100, 26, '', 'Average performance sit up', NOW(), NOW()),
(347, 9, 25, 104, 22, 'Be always ready to learn', 'Average performance sit up with your academics', NOW(), NOW()),
(353, 9, 25, 88, 38, 'Always try to be a strong student', 'Average performance sit up with your academics', NOW(), NOW()),
(346, 9, 25, 88, 38, 'Try to always be regular in school', 'Average performance try harder next term', NOW(), NOW()),
(370, 9, 25, 108, 18, 'Julianah is well behaved in the class.', 'Fair attempt. Sit up.', NOW(), NOW()),
(337, 9, 25, 112, 14, 'You need to put in your best', 'Average performance sit up', NOW(), NOW()),
(372, 9, 25, 126, 0, 'Emmanuella is well behaved in the class', 'Fairly good attempt. Sit up still.', NOW(), NOW()),
(344, 9, 25, 116, 10, 'Work on your vocabulary', 'Fair results be serious with your academics', NOW(), NOW()),
(352, 9, 25, 110, 16, 'More agility is required', 'Average performance you can do better than this next term', NOW(), NOW()),
(363, 9, 25, 0, 0, '', 'Very poor result', NOW(), NOW()),
(396, 9, 25, 126, 0, 'She has good behavior', 'Good result.  Keep it up.', NOW(), NOW()),
(373, 9, 25, 126, 0, 'Hussenate is a well behaved student', 'Fair attempt. Sit up!', NOW(), NOW()),
(374, 9, 25, 102, 24, 'Ezekiel is very playful in the class', 'Poor result. Sit up!', NOW(), NOW()),
(375, 9, 25, 114, 12, 'Timileyi is a well behaved student', 'Fair attempt. Try harder next term.', NOW(), NOW()),
(401, 9, 25, 116, 110, 'Blessing is attentive in class and does her work well', 'Fair attempt.  Try harder still.', NOW(), NOW()),
(408, 9, 25, 126, 0, 'Rachel is calm and attentive in class', 'Good result. Keep it up.', NOW(), NOW()),
(402, 9, 25, 126, 0, 'Victoria is active in class and always ready to learn', 'Good result.  Keep it up.', NOW(), NOW()),
(404, 9, 25, 126, 0, 'James needs to focus more on his studies', 'Fair attempt.  Sit up!', NOW(), NOW()),
(415, 9, 25, 126, 0, 'Keji is hardworking and very attentive in class', 'Very good result.  Keep it up, Keji!', NOW(), NOW()),
(378, 9, 25, 126, 126, 'Adeola is a  well behaved in the class', 'Fairly good result. Try harder still', NOW(), NOW()),
(431, 9, 25, 124, 2, 'She is an-easy going person but not courageous', 'Very good result. Keep it up, Aliu.', NOW(), NOW()),
(432, 9, 25, 116, 10, 'She is ready to learn but needs to be encouraged', 'Fair attempt. Try harder!', NOW(), NOW()),
(416, 9, 25, 102, 24, 'Victor is quiet and respectful', 'Good result.  Keep it up!', NOW(), NOW()),
(433, 9, 25, 112, 14, 'He is ready to learn but very lazy', 'Fair attempt.  Sit up.', NOW(), NOW()),
(434, 9, 25, 94, 32, 'He is ready to learn but not organized', 'Poor academic performance.  Sit up.', NOW(), NOW()),
(437, 9, 25, 120, 6, 'He is an easy-going person  easily annoyed', 'A very good academic report.  Keep it up, girl.', NOW(), NOW()),
(376, 9, 25, 116, 10, 'Oyinkasola is well behaved in the class.', 'Poor result. Sit up!', NOW(), NOW()),
(379, 9, 25, 112, 14, 'Nifemi is well behaved in the class.', 'Poor result. Sit up, please.', NOW(), NOW()),
(446, 9, 25, 74, 52, 'He is ready to learn but needs to be encouraged', 'Poor result.  Try harder!', NOW(), NOW()),
(380, 9, 25, 124, 2, 'Grace is not devoted to his her studies.', 'Poor result. Sit up.', NOW(), NOW()),
(381, 9, 25, 116, 10, 'Faith is well behaved in class', 'Faith is a hardworking girl. Try to improve on your weak areas.', NOW(), NOW()),
(421, 9, 25, 122, 4, 'Samuel needs to be more serious with his studies', 'Fair attempt.  Try harder.', NOW(), NOW()),
(382, 9, 25, 126, 0, 'Hassan is quiet in class.', 'Fair result. Try harder.', NOW(), NOW()),
(397, 9, 25, 126, 0, 'She is an enthusiastic learner', 'An excellent academic performance. Please, do not relent.', NOW(), NOW()),
(383, 9, 25, 124, 2, 'Daniella is not very active in class activities.', 'Fair academic attempt. Try harder, still.', NOW(), NOW()),
(384, 9, 25, 116, 10, 'Saratu is a well behaved student', 'Poor result. Sit up, please.', NOW(), NOW()),
(386, 9, 25, 110, 16, 'Uche is a well behaved student.', 'Fair attempt. Sit up.', NOW(), NOW()),
(389, 9, 25, 124, 2, 'Abideen is very dedicated and devoted to his academics.', 'Abideen is very industrious. Please, do not relent.', NOW(), NOW()),
(392, 9, 25, 111, 15, 'John participates actively in class activities.', 'Good academic performance. Keep it up, John.', NOW(), NOW()),
(393, 9, 25, 124, 2, 'Ewajesu is a well behaved student.', 'Fairly good attempt. You can surpass this performance. I know you can. Just put in the required work', NOW(), NOW()),
(395, 9, 25, 126, 0, 'Victor easily gets distracted during class lessons.', 'Poor result. Sit up.', NOW(), NOW()),
(430, 9, 25, 100, 26, 'Success needs to avoid distractions and pay more attention to his studies', 'Very poor result.', NOW(), NOW()),
(425, 9, 25, 116, 10, 'Firdausi is calm,respectful and attentive in class', 'Good result. Keep it up!', NOW(), NOW()),;
