INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(398, 9, 25, 122, 4, 'He is a good boy', 'Good result.  Keep it up.', NOW(), NOW()),
(399, 9, 25, 126, 0, 'He is a good boy', 'Fair attempt.  Sit up.', NOW(), NOW()),
(400, 9, 25, 126, 0, 'He exibits a positive attitude in the classroom', 'Fair attempt. Try harder.', NOW(), NOW()),
(403, 9, 25, 126, 0, 'She shows ethusiasm for classroom activities', 'Good result.  Keep it up.', NOW(), NOW()),
(405, 9, 25, 126, 0, 'He is a good boy', 'An excellent academic performance.  Keep it up.', NOW(), NOW()),
(407, 9, 25, 124, 0, 'He always pays attention in the class', 'Good result Keep it up.', NOW(), NOW()),
(411, 9, 25, 120, 0, 'He pays attention in the class', 'Fair attempt.  Sit up.', NOW(), NOW()),
(412, 9, 25, 126, 0, 'He shows enthusiasm for classroom activities', 'A very good academic report. Keep it up.', NOW(), NOW()),
(413, 9, 25, 126, 0, 'He exibits a positive attitude in the classroom', 'Good academic performance.  Keep it up.', NOW(), NOW()),
(414, 9, 25, 122, 4, 'He exibits a positive attitude in the class', 'Fair attempt.  Sit up.', NOW(), NOW()),
(417, 9, 25, 126, 0, 'Shows enthusiasm for classroom activities', 'Fair attempt.  Sit up.', NOW(), NOW()),
(420, 9, 25, 126, 0, 'Shows enthusiasm for classroom activities', 'Good result. Keep it up!', NOW(), NOW()),
(423, 9, 25, 126, 0, 'He is a good boy', '', NOW(), NOW()),
(426, 9, 25, 124, 2, 'He is a good boy', 'Fair attempt. Sit up.', NOW(), NOW()),
(427, 9, 25, 126, 0, 'He is a good boy', 'Fair attempt. Sit up!', NOW(), NOW()),
(406, 9, 25, 126, 0, 'Testimony is very attentive in class and respectful', 'Good result. Keep it up.', NOW(), NOW()),
(410, 9, 25, 126, 0, 'Victory is well behaved and attentive in class', 'Good academic performance.  Keep it up.', NOW(), NOW()),
(429, 9, 25, 116, 10, 'Mohammed needs to pay more attention to his studies', 'Poor performance. Sit up, Mohammed.', NOW(), NOW()),
(428, 9, 25, 120, 6, 'Abideen needs to concentrate more in his studies', '', NOW(), NOW()),
(418, 9, 25, 126, 0, 'She exibits a positive attitude in the classroom', 'Good result.  Keep it up!', NOW(), NOW()),
(355, 9, 25, 0, 0, '', '', NOW(), NOW()),
(398, 9, 26, 110, 6, 'He is a happy student who loves school', 'Good result. Keep it up, boy.', NOW(), NOW()),
(412, 9, 26, 112, 4, 'He is a good student, who always puts his best foot forward', 'Excellent! Please, do not relent.', NOW(), NOW()),
(427, 9, 26, 108, 8, 'He often gets distracted in class', 'Fair attempt.  Sit  up', NOW(), NOW()),
(426, 9, 26, 112, 4, 'A well behaved student', 'Fair attempt.  Sit up.', NOW(), NOW()),
(407, 9, 26, 112, 4, 'He is well behaved', 'Good result.  Keep it up', NOW(), NOW()),
(400, 9, 26, 116, 0, 'He comports himself well in class', 'Fairly good result.  Try harder still', NOW(), NOW()),
(429, 9, 26, 116, 0, 'A well behaved student', 'Poor attempt.  Sit up, please.', NOW(), NOW()),
(396, 9, 26, 116, 0, 'She is well behaved in class', 'Good result.  Keep it up', NOW(), NOW()),
(418, 9, 26, 116, 0, 'She often gets distracted in class', 'Very good result.  Keep it up, girl.', NOW(), NOW()),
(397, 9, 26, 116, 0, 'She pays attention to details', 'Excellent academic performance.  Keep it up, Obiita.', NOW(), NOW()),
(403, 9, 26, 104, 12, 'She is well behaved', 'Fair attempt.  Try harder', NOW(), NOW()),
(420, 9, 26, 108, 8, 'She often gets distracted in class', 'Good result.  Keep it up.', NOW(), NOW()),
(342, 9, 26, 116, 0, 'Sheâ€™s a good girl but she need to put more effort when it comes too academics.', 'Fair results sit up please', NOW(), NOW()),
(413, 9, 26, 112, 4, 'A happy student', 'Very good academic performance.  Keep it up, Emma.', NOW(), NOW()),
(417, 9, 26, 112, 4, 'A well behaved student', 'Fair attempt.  You can do better than this, Lekan.', NOW(), NOW()),
(399, 9, 26, 114, 2, 'Well behaved in class', 'Fair attempt.  Sit up.', NOW(), NOW()),
(411, 9, 26, 112, 4, 'A well behaved student', 'Good result.  Try harder still.', NOW(), NOW()),
(423, 9, 26, 116, 0, 'A well behaved student', 'Fair attempt. Try harder.', NOW(), NOW()),
(419, 9, 26, 116, 0, 'An enthusiastic learner', 'Good result.  Keep it up.', NOW(), NOW()),
(414, 9, 26, 114, 2, 'A happy student', 'Fair attempt.  You can surpass this, Nwanze.', NOW(), NOW()),
(405, 9, 26, 112, 4, 'A happy student', 'Excellent academic report.  Keep it up, boy!', NOW(), NOW()),
(379, 9, 26, 106, 10, 'Nifemi is not dedicated to her academics. She rarely do her assignments and copy notes in class.', 'Poor attempt.  Sit up.', NOW(), NOW()),
(380, 9, 26, 110, 6, 'Grace is quiet in the class but she needs to start making friends with people who are very serious w', 'Poor result. Wake up, please', NOW(), NOW()),
(381, 9, 26, 106, 10, 'Faith is good and well-behaved in class.', 'Good result.  Keep it up.', NOW(), NOW()),
(383, 9, 26, 114, 2, 'Daniella easily gets distracted by the unserious students during lessons.', 'Fair attempt. Try harder still.', NOW(), NOW()),
(370, 9, 26, 102, 14, 'Juliana is a well behaved student.', 'Fair attempt.  Try harder still.', NOW(), NOW()),
(386, 9, 26, 106, 10, 'Uche is quite in class but he should stop allowing his friends to distract him during lectures.', 'Fair attempt.  You can do better.', NOW(), NOW()),
(389, 9, 26, 116, 0, 'Abideen has been very consistent in maintaining academic excellence but he can be very noisy in clas', 'Very good academic performance.  Keep it up, boy.', NOW(), NOW()),
(395, 9, 26, 114, 2, 'Victor is always quarreling with the girls in his class.', 'Fair attempt. Sit up.', NOW(), NOW()),
(372, 9, 26, 112, 4, 'Emmanuella should learn to pay attention during lessons.', 'Fairly good result. Try harder', NOW(), NOW()),
(373, 9, 26, 114, 2, 'Hussenait is very respectful towards her teachers.', 'Fair attempt. Sit up still', NOW(), NOW()),
(401, 9, 26, 116, 0, 'Blessing is attentive in class and does her work well', 'Good result.  Keep it up.', NOW(), NOW()),
(374, 9, 26, 110, 6, 'Ezekiel is very playful in the class. He hardly concentrate when a teacher is teaching.', 'Poor attempt.  Sit up please.', NOW(), NOW()),
(375, 9, 26, 114, 2, 'Timileyi is very dedicated to his academics but the inability of his parents to pay his school fees ', '', NOW(), NOW()),
(402, 9, 26, 110, 6, 'Victoria is active in class and always ready to learn', 'A very good academic report.  Keep it up, Vicky.', NOW(), NOW()),
(376, 9, 26, 108, 8, 'Oyinkasola is a well behaved student but she should start making friends with people that can challe', 'Poor attempt. Sit up.', NOW(), NOW()),
(378, 9, 26, 114, 2, 'Adeola is a well behaved student.', 'Fair attempt.  Try harder still.', NOW(), NOW()),
(326, 9, 26, 110, 6, 'Sheâ€™s well behaved and lovely to be with.', 'Excellent performance keep it', NOW(), NOW()),
(406, 9, 26, 116, 0, 'Testimony is very attentive in class and respectful', 'Good result.  Keep it up, Testimony.', NOW(), NOW()),
(330, 9, 26, 116, 0, 'Gentle, brilliant and well mannered.', 'Excellent result keep it up', NOW(), NOW()),
(327, 9, 26, 116, 0, 'Gentle and well mannered.', 'Average performance', NOW(), NOW()),
(331, 9, 26, 110, 6, 'Goodluck is a good boy but need to put more seriousness in his academics.', 'Very poor result sit up with focus', NOW(), NOW()),
(339, 9, 26, 116, 0, 'Sheâ€™s a good girl and well behaved', 'Excellent result', NOW(), NOW()),
(340, 9, 26, 116, 0, 'Sheâ€™s a good girl and well behaved', 'Good performance', NOW(), NOW()),
(341, 9, 26, 114, 2, 'Beautiful in and out and well mannered.', 'Good results but you do more better than this', NOW(), NOW()),
(404, 9, 26, 106, 10, 'James is calm and well behaved.He needs to focus more on his studies', 'Fair attempt. Sit up.', NOW(), NOW()),
(408, 9, 26, 114, 2, 'Rachel is calm and attentive in class', 'Good result.  Keep it up.', NOW(), NOW()),
(410, 9, 26, 116, 0, 'Victory is well behaved and attentive in class', 'Good result. Keep it up, Isaac.', NOW(), NOW()),
(415, 9, 26, 110, 6, 'Keji is hardworking and very attentive in class', 'Very good result. Keep it up, girl.', NOW(), NOW()),
(354, 9, 26, 114, 2, 'He exhibits a positive outlook and attitude in the classroom.', 'Very good performance', NOW(), NOW()),
(421, 9, 26, 114, 2, 'Samuel is very active in class but needs to pay more attention to his studies', 'Fair attempt. Sit up next term.', NOW(), NOW()),
(355, 9, 26, 114, 2, 'Sheâ€™s so smart and well mannered.', 'Average performance sit up please', NOW(), NOW()),
(425, 9, 26, 106, 10, 'Firdausi is calm,respectful and attentive in class', '', NOW(), NOW()),
(356, 9, 26, 112, 4, 'Sheâ€™s serious in her academics but need to work on her temperament.', 'Very good performance', NOW(), NOW()),
(428, 9, 26, 108, 8, 'Abideen is active in class,but he needs to concentrate more in his studies', '', NOW(), NOW()),
(357, 9, 26, 112, 4, 'Sheâ€™s a good girl and well behaved', 'Fair results sit up with target', NOW(), NOW()),
(358, 9, 26, 116, 0, 'Heâ€™s a good boy and need to put more effort in his work.', 'Poor performance sit up and focus', NOW(), NOW()),
(359, 9, 26, 114, 2, 'Sheâ€™s a good girl and well behaved', 'Average performance sit up', NOW(), NOW()),
(361, 9, 26, 114, 2, 'Heâ€™s a good boy and ready to learn.', 'Average performance try harder next term', NOW(), NOW()),
(362, 9, 26, 105, 12, 'Heâ€™s always active and ready to learn more', 'Very good performance', NOW(), NOW()),
(363, 9, 26, 114, 2, 'Sheâ€™s a good girl and well behaved but need to put more effort in her academics.', 'Fair results sit up with', NOW(), NOW()),
(364, 9, 26, 114, 2, 'He takes great pride in his work.', 'Excellent performance keep it up', NOW(), NOW()),
(366, 9, 26, 108, 8, 'Heâ€™s a good boy but need to put more effort in his academics.', 'Very poor result sit up', NOW(), NOW()),
(367, 9, 26, 112, 4, 'Heâ€™s a good boy and ready to learn.', 'Average performance try harder next term', NOW(), NOW()),
(384, 9, 26, 110, 6, 'Saratu is too playful in class.', 'Fair attempt.  Sit up please.', NOW(), NOW()),
(392, 9, 26, 116, 0, 'John is a well behaved student.', 'Good academic performance. Keep it up.', NOW(), NOW()),
(328, 9, 26, 106, 10, 'She is committed to doing her best', 'Good performance', NOW(), NOW()),
(332, 9, 26, 110, 6, 'She often struggles to focus in class', 'Good performance', NOW(), NOW()),
(333, 9, 26, 114, 2, 'She needs to pay more attention while teaching is going on', 'Very good performance', NOW(), NOW()),
(334, 9, 26, 102, 14, 'Improvement on her relationship with others is necessary', 'Poor result sit up', NOW(), NOW()),
(335, 9, 26, 110, 6, 'She needs to be more serious with academics work', 'Fair results sit up', NOW(), NOW()),
(336, 9, 26, 110, 6, 'She needs to work more harder', 'Average performance sit up', NOW(), NOW()),
(337, 9, 26, 114, 2, 'She exhibits a positive attitude in the class', 'Average performance', NOW(), NOW()),
(338, 9, 26, 116, 0, 'She takes an active part in class discussions', 'Excellent performance keep it', NOW(), NOW()),
(344, 9, 26, 112, 4, 'He needs to focus more on reading and writing', 'Fair results sit up', NOW(), NOW()),
(346, 9, 26, 60, 56, 'She needs to be more zealous', 'Failed', NOW(), NOW()),
(347, 9, 26, 108, 8, 'More seriousness with positive utterances is required of you', 'Fair results sit up', NOW(), NOW()),
(348, 9, 26, 104, 2, 'He needs to reduce his play.', 'Fair results sit up', NOW(), NOW()),
(349, 9, 26, 116, 0, 'He shows maturity when solving problems', 'Excellent result keep it up', NOW(), NOW()),;
