INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(413, 8, 22, 118, 0, 'Emmanuel is well behaved in class', 'Good result. Keep it up.', NOW(), NOW()),
(355, 8, 22, 120, 6, 'Esther is inquisitive in class and friendly', 'Good', NOW(), NOW()),
(361, 8, 22, 116, 10, 'David is active in his class work and respectful', 'Average performance you can do better than this dear', NOW(), NOW()),
(414, 8, 22, 112, 6, 'Nwanze is well behaved in class', 'Good result. Kept it up.', NOW(), NOW()),
(359, 8, 22, 126, 0, 'She makes friends easily and willing to learn', 'Fair result try harder next term', NOW(), NOW()),
(415, 8, 22, 116, 2, 'Morenikeji behaves well in class', 'Good result. Keep it up, Keji', NOW(), NOW()),
(358, 8, 22, 122, 4, 'He is inquisitive obedient and ready to learn', 'Fair result try harder next term', NOW(), NOW()),
(416, 8, 22, 108, 10, 'Victor participates actively in class activities', 'Good result. Keep it up.', NOW(), NOW()),
(357, 8, 22, 126, 0, 'She is friendly and always willing to learn', 'Fair result try harder next term', NOW(), NOW()),
(417, 8, 22, 114, 4, 'Lekan is always restless and can hardly stay at a place', 'Poor result. Sit up.', NOW(), NOW()),
(356, 8, 22, 122, 4, 'She is obedient, respectful and jovial', 'Very good result', NOW(), NOW()),
(418, 8, 22, 118, 0, 'Mercy is a well behaved student', 'Good result. Keep it up.', NOW(), NOW()),
(419, 8, 22, 118, 0, 'Esther is well behaved student', 'Good result. But you can do better, Esther.', NOW(), NOW()),
(420, 8, 22, 118, 0, 'Anjola is a well behaved student', 'Good result. Keep it up, Anjola.', NOW(), NOW()),
(421, 8, 22, 116, 2, 'Samuel is very playful in class', 'Fair attempt. Sit up!', NOW(), NOW()),
(422, 8, 22, 62, 56, 'Shola is always causing trouble in class', 'Poor result. Sit up', NOW(), NOW()),
(423, 8, 22, 118, 0, 'Ramadan is a well behaved student', 'Fair attempt. Try harder next term.', NOW(), NOW()),
(424, 8, 22, 116, 2, 'Amira is very serious with her studies', 'Brilliant academic performance. Keep it up, Amirat.', NOW(), NOW()),
(425, 8, 22, 124, 2, 'Firduasi needs to put more efforts in her studies', 'Good result. Keep it up.', NOW(), NOW()),
(426, 8, 22, 124, 2, 'Ademola is quiet in class', 'Fair attempt. Sit up, Raji.', NOW(), NOW()),
(427, 8, 22, 124, 2, 'Abdulahi is very quite in class', 'Poor result. Sit up.', NOW(), NOW()),
(428, 8, 22, 108, 18, 'Abideen is not serious at all with his studies', 'Poor result. Sit up.', NOW(), NOW()),
(429, 8, 22, 118, 8, 'Muhammed is not serious with his studies', 'Poor result. Sit up.', NOW(), NOW()),
(430, 8, 22, 98, 28, 'Success is never serious with his studies', 'Very poor attempt. Be serious.', NOW(), NOW()),
(360, 8, 22, 112, 14, 'He is attentive in class and active in his class activity', '', NOW(), NOW()),
(326, 8, 22, 116, 2, '', '', NOW(), NOW()),
(328, 8, 23, 116, 2, 'Well behaved girl', 'Excellent performance keep it up', NOW(), NOW()),
(425, 8, 23, 112, 6, 'Firdausi is a well behaved student', 'Fair attempt. Try harder.', NOW(), NOW()),
(326, 8, 23, 108, 2, 'She is obedient and active in class work', 'Good results keep it up although there is room for improvement', NOW(), NOW()),
(426, 8, 23, 104, 14, 'Raji is very quiet in class', 'Fair results kindly sit up', NOW(), NOW()),
(427, 8, 23, 118, 0, 'Abdulahi is very quite in class', 'Poor performance. You can do better than this.', NOW(), NOW()),
(428, 8, 23, 112, 6, 'Abideen is not serious with his studies and doesnt  want to improve', 'Poor attempt. Sit up, Abideen.', NOW(), NOW()),
(429, 8, 23, 114, 4, 'Abdulaziz should become serious with his studies', 'Poor result. Try harder.', NOW(), NOW()),
(430, 8, 23, 80, 38, 'Success is never serious with his academics', 'Very poor performance. Try harder.', NOW(), NOW()),
(441, 8, 23, 116, 4, 'Desola has zealous attitude towards learning, keep on the strive.', 'Fair attempt. Try harder next term.', NOW(), NOW()),
(436, 8, 23, 120, 0, 'Yetunde is having steady improvement in most subjects, get serious with others for complete improvem', 'Good result. Try harder still.', NOW(), NOW()),
(368, 8, 23, 114, 4, 'She needs to more serious.', 'Good performance', NOW(), NOW()),
(442, 8, 23, 120, 0, 'Rachael has zealous attitude towards learning', 'Good result. Try harder still.', NOW(), NOW()),
(443, 8, 23, 116, 4, 'Sofiano is interested in learning but easily distracted', 'Fairly good result.  Try harder next term.', NOW(), NOW()),
(396, 8, 23, 114, 4, 'Divine actively participates in class activities', 'Fair attempt. Please pay attention to areas you have shown weakness, especially in science subjects.', NOW(), NOW()),
(444, 8, 23, 114, 6, 'An attentive and well behaved student', '', NOW(), NOW()),
(369, 8, 23, 118, 0, 'She is so simple and gentle', 'Average performance try harder next term', NOW(), NOW()),
(370, 8, 23, 108, 10, 'She needs to be more attentive and forcus in class', 'Average performance put more effort next term', NOW(), NOW()),
(371, 8, 23, 116, 2, 'She is always cheerful', 'Good results but there is room to improve', NOW(), NOW()),
(372, 8, 23, 112, 6, 'She needs to shun laziness and always awake.', 'Good performance but try harder next term', NOW(), NOW()),
(374, 8, 23, 112, 6, 'His character not too impressive', 'Average performance be serious with  your academics', NOW(), NOW()),
(375, 8, 23, 118, 0, 'This student is strong willed', 'Good performance keep it up and improve', NOW(), NOW()),
(376, 8, 23, 116, 2, 'She should learn to keep quiet in class', 'Average performance be serious with your academics activities', NOW(), NOW()),
(377, 8, 23, 118, 0, 'Your love for learning is impressive', 'Good results', NOW(), NOW()),
(327, 8, 23, 116, 2, 'She is calm and inquisitive in class', 'Average performance try harder next term', NOW(), NOW()),
(378, 8, 23, 114, 4, 'She is a simple hearted student', 'Average performance be serious with your academics', NOW(), NOW()),
(379, 8, 23, 118, 0, 'Her attitude towards learning is poor', 'Fair results be serious with your academics', NOW(), NOW()),
(447, 8, 23, 120, 0, 'A very quiet and well behaved student', 'Fair academic attempt. You have the potential to do better. Sit up and unleash the genius in you.', NOW(), NOW()),
(380, 8, 23, 114, 4, 'She needs to be more serious', 'Fair results put more effort to your academics', NOW(), NOW()),
(381, 8, 23, 116, 2, 'This is a determined student', 'Good performance', NOW(), NOW()),
(382, 8, 23, 118, 0, 'He should put more effort in learning', 'Average performance try harder next term', NOW(), NOW()),
(383, 8, 23, 118, 0, 'You should try not to be lazy', 'Fair results be serious with your academics please', NOW(), NOW()),
(384, 8, 23, 112, 8, 'Her performance not impressive', 'Fair results try harder next term', NOW(), NOW()),
(385, 8, 23, 116, 2, 'Your best is not enough try more', 'Good results but there is room for improvement', NOW(), NOW()),
(330, 8, 23, 118, 0, 'She is intelligent and up and doing towards her class activities', 'Excellent result keep it up', NOW(), NOW()),
(386, 8, 23, 95, 23, 'Try to behave like a boy', 'Fail results', NOW(), NOW()),
(331, 8, 23, 86, 32, 'He is friendly but get carried away easily in class', 'Poor result sit up', NOW(), NOW()),
(387, 8, 23, 0, 0, 'Out of school', '', NOW(), NOW()),
(388, 8, 23, 116, 2, 'She is a self motivated student', 'Good performance keep it up', NOW(), NOW()),
(339, 8, 23, 114, 4, 'She is respectful and cool headed in class', 'Very good performance keep it up', NOW(), NOW()),
(389, 8, 23, 118, 0, 'This school is so proud to have a student like you', 'Excellent performance although there is still room for more', NOW(), NOW()),
(390, 8, 23, 118, 0, 'Learn to be fast in learning', 'Good results but you can do better than this next term', NOW(), NOW()),
(391, 8, 23, 118, 0, 'Try to improve on yourself', 'Very good performance', NOW(), NOW()),
(393, 8, 23, 116, 2, 'Desire more to improve on yourself', 'Average performance try harder next term', NOW(), NOW()),
(394, 8, 23, 108, 10, 'She is a free hearted student', 'Fair results be serious with your academics', NOW(), NOW()),
(395, 8, 23, 118, 0, 'You have a positive attitude', 'Average performance put more effort', NOW(), NOW()),
(340, 8, 23, 118, 0, 'She is friendly and inquisitive in class', 'Average performance try harder next term', NOW(), NOW()),
(341, 8, 23, 116, 2, 'She is active in her class activities and ready to learn', 'Average performance kindly  sit up', NOW(), NOW()),
(397, 8, 23, 114, 4, 'Obita is very serious with her studies', 'Very good academic performance. Keep it up.', NOW(), NOW()),
(398, 8, 23, 116, 2, 'Victor is well behaved in class', 'Good result. However, work on the areas you have shown weakness.', NOW(), NOW()),
(399, 8, 23, 118, 0, 'David is a well behaved student', 'Poor attempt. Sit up!', NOW(), NOW()),
(401, 8, 23, 60, 58, 'Blessing is quite in class', '', NOW(), NOW()),
(400, 8, 23, 116, 2, 'Roland is very playful in class', 'Not- so-good an academic report. Sit up, Roland.', NOW(), NOW()),
(402, 8, 23, 116, 2, 'Victoria participates actively in class activities', 'Good result. Work harder, still.', NOW(), NOW()),
(404, 8, 23, 118, 0, 'James can be easily distracted in class', 'poor attempt. Sit up!', NOW(), NOW()),
(405, 8, 23, 116, 2, 'Havilah is very devoted to his academics', 'Brilliant academic performance. Keep it up, Labija.', NOW(), NOW()),
(406, 8, 23, 116, 2, 'Testimony is a well behaved student', 'Good academic report. Keep it up, Nduche.', NOW(), NOW()),
(408, 8, 23, 116, 2, 'Rachel is well behaved in the class', 'Fairly good result. You can do better than this, Racheal.', NOW(), NOW()),
(409, 8, 23, 114, 4, 'Uwem is very playful in the class', 'Sit up, Uwem.', NOW(), NOW()),
(411, 8, 23, 106, 12, 'Joseph plays alot in the class', 'Poor attempt. Sit up, Joseph.', NOW(), NOW()),
(412, 8, 23, 110, 8, 'Enoch is very devoted and dedicate to his studies', 'Brilliant academic performance. Keep it up, Agboola.', NOW(), NOW()),
(413, 8, 23, 118, 0, 'Emmanuel is well behaved in the class', 'Brilliant academic report. Keep it up, Abebe.', NOW(), NOW()),
(416, 8, 23, 108, 10, 'Victor is well behaved in the class', 'Good result. Keep it up.', NOW(), NOW()),
(414, 8, 23, 112, 6, 'David is well behaved in the class', 'This is not a reflection of your academic prowess, David. What went wrong?', NOW(), NOW()),
(415, 8, 23, 116, 2, 'Morenikeji behaves well in class', 'Pay attention to your areas of weakness, Keji. Good result, still.', NOW(), NOW()),
(417, 8, 23, 114, 4, 'Lekan is always restless and can hardly stay at a place', 'Poor attempt. Sit up.', NOW(), NOW()),
(418, 8, 23, 118, 0, 'Mercy is a well behaved student', 'Good result. Keep it up, Mercy.', NOW(), NOW()),
(419, 8, 23, 118, 0, '', 'Good result. Try harder still.', NOW(), NOW()),
(420, 8, 23, 118, 0, 'Anjola is a well behaved student', 'Good result. Keep it up.', NOW(), NOW()),
(421, 8, 23, 116, 2, 'Samuel is very playful in class', 'Sit up, Samuel.', NOW(), NOW()),
(422, 8, 23, 62, 56, 'Shola is too playful in the class', 'Poor result. Sit up, Shola.', NOW(), NOW()),
(423, 8, 23, 118, 0, 'Ramadan is a well behaved student', 'Fair attempt. Try harder.', NOW(), NOW()),
(424, 8, 23, 116, 2, 'Amira is very serious with her studies', 'Very good result. Keep it up.', NOW(), NOW()),
(431, 8, 23, 114, 4, 'She is very smart and always ready to learn', 'Good result. Keep it up', NOW(), NOW()),
(432, 8, 23, 116, 2, 'Ope is easily distracted and this affects her concentration.', 'Poor attempt. Sit up!', NOW(), NOW()),;
