INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(461, 8, 22, 65, 4, 'This is the teachers comment', 'This boy is a very good student', NOW(), NOW()),
(462, 8, 22, 0, 0, '', 'This is the principal comment', NOW(), NOW()),
(328, 8, 22, 116, 2, 'Well mannered girl.', 'Excellent result keep it up', NOW(), NOW()),
(463, 8, 22, 0, 0, '', '', NOW(), NOW()),
(431, 8, 22, 114, 4, 'She is very smart and always ready to learn', 'Very good result keep it up', NOW(), NOW()),
(333, 8, 22, 118, 0, 'Very brilliant girl', 'Good results', NOW(), NOW()),
(432, 8, 22, 116, 2, 'She is active in class and communicates well with her mates', 'Poor academic performance. Sit up, Ayedu.', NOW(), NOW()),
(433, 8, 22, 114, 12, 'Solomon is too playful. He needs to concentrate more in his studies for better performance', 'Poor academic performance. Get more serious next term.', NOW(), NOW()),
(437, 8, 22, 118, 0, 'She is a very smart and always ready to learn', 'A very good academic performance. Abigail is very hardworking. Please, do not relent.', NOW(), NOW()),
(438, 8, 22, 102, 16, 'He friendly and relates well with his peers', 'Below average academic performance. Sit up.', NOW(), NOW()),
(436, 8, 22, 120, 0, 'Shun distractions, give your time to acquiring as much knowledge as possible at this stage for impro', 'Fairly good result. Try harder', NOW(), NOW()),
(439, 8, 22, 114, 6, 'Minimise your play and concentrate more on academics for better performance', 'Fair attempt. Try harder.', NOW(), NOW()),
(440, 8, 22, 124, 2, 'Shun distractions, give your time to acquiring as much knowledge as possible at this stage for impro', 'Good result. Try harder, still.', NOW(), NOW()),
(441, 8, 22, 116, 4, 'Give more time to academics and avoid distractions for better performance.', 'Below average academic performance. Sit up.', NOW(), NOW()),
(443, 8, 22, 122, 4, 'Avoid playfulness, get more serious with your academics for better performance.', 'Fair attempt. Try harder.', NOW(), NOW()),
(444, 8, 22, 118, 8, 'Avoid bad influence for continuous improvement and performance', 'Good result. keep it up.', NOW(), NOW()),
(447, 8, 22, 118, 8, 'Playful and unserious attitude towards learning', 'Not-so-good a report. Sit up, Alfred.', NOW(), NOW()),
(368, 8, 22, 118, 0, 'She is a well out spoken student.', 'Average result try harder next term', NOW(), NOW()),
(448, 8, 22, 120, 6, 'He is very stubborn and indolent', 'Poor academic report. Sit up', NOW(), NOW()),
(351, 8, 22, 114, 4, 'Well reserved boy', 'Good results', NOW(), NOW()),
(349, 8, 22, 118, 0, 'Well behaved', 'Very good result keep it up', NOW(), NOW()),
(332, 8, 22, 116, 2, 'Well behaved girl', 'Good result', NOW(), NOW()),
(348, 8, 22, 108, 10, 'Well behaved', 'Good results', NOW(), NOW()),
(344, 8, 22, 118, 0, 'Good boy', 'Fair result try harder next term', NOW(), NOW()),
(336, 8, 22, 112, 6, 'Always smiling', 'Average performance you can do better than this', NOW(), NOW()),
(450, 8, 22, 104, 22, 'Bukola needs to focus more on her studies for a better result.', 'Average academic performance. Sit up.', NOW(), NOW()),
(457, 8, 22, 110, 16, 'Daniel needs to concentrate more on his studies next term.', 'Poor academic performance. Sit up.', NOW(), NOW()),
(459, 8, 22, 110, 16, 'A fair performance there is room for improvement next term.', 'Fair attempt. Sit up', NOW(), NOW()),
(451, 8, 22, 116, 10, 'Put in more effort for a better result next term', 'Fairly good result. Try harder next term.', NOW(), NOW()),
(452, 8, 22, 112, 14, 'Fareedah needs to concentrate more on her studies', 'Fair attempt. Sit up.', NOW(), NOW()),
(453, 8, 22, 118, 8, 'She is an easy-going person but very deceitful', 'Below average performance. Try harder.', NOW(), NOW()),
(454, 8, 22, 124, 2, 'She is very associative but not very organised', 'Poor result. Sit up.', NOW(), NOW()),
(343, 8, 22, 116, 2, 'Very brilliant girl', 'Excellent result keep it up', NOW(), NOW()),
(350, 8, 22, 116, 2, 'Well behaved', 'Good results', NOW(), NOW()),
(346, 8, 22, 108, 10, 'Positive minded', 'Good results keep it up', NOW(), NOW()),
(352, 8, 22, 114, 4, 'Impressive', 'Good performance but you can still do better than this', NOW(), NOW()),
(347, 8, 22, 108, 10, 'Good boy', 'Average result', NOW(), NOW()),
(335, 8, 22, 116, 2, 'She is always on her own in class', 'Average performance please sit up', NOW(), NOW()),
(337, 8, 22, 100, 18, 'Too quite', 'Poor result sit up', NOW(), NOW()),
(353, 8, 22, 102, 16, 'Well mannered boy', 'Good results', NOW(), NOW()),
(458, 8, 22, 124, 2, 'He is very humble but very indolent', 'Poor academic performance. Nsofor should get more serious with his studies and play less.', NOW(), NOW()),
(329, 8, 22, 112, 6, 'Well behaved girl', 'Average performance try harder next term', NOW(), NOW()),
(338, 8, 22, 118, 0, 'Well behaved', 'Good results', NOW(), NOW()),
(345, 8, 22, 90, 28, 'Good instructor', 'Excellent result keep it up', NOW(), NOW()),
(455, 8, 22, 106, 20, 'He is very gentle, cool and calm but very lazy', 'Poor result. Work harder.', NOW(), NOW()),
(460, 8, 22, 116, 10, 'She is an easy- going person and possesses leadership traits', 'Poor academic performance. You can do better than this, Justina.', NOW(), NOW()),
(397, 8, 22, 114, 4, 'Obita is very serious with her studies', 'Brilliant academic report. Keep it up', NOW(), NOW()),
(449, 8, 22, 114, 12, 'He is very stubborn and fond of speaking vernacular', 'Discouraging academic report.', NOW(), NOW()),
(398, 8, 22, 116, 2, 'Victor should be more serious with his studies', 'Good result. Try harder still.', NOW(), NOW()),
(399, 8, 22, 118, 0, 'David should get serious with his studies', 'Poor result. Sit up.', NOW(), NOW()),
(400, 8, 22, 116, 2, 'He gets easily distracted in class', 'Fairly good result. Sit up', NOW(), NOW()),
(456, 8, 22, 102, 24, 'He is very skilfull but not very discipline', 'Poor academic report. Sit up.', NOW(), NOW()),
(326, 8, 22, 116, 2, 'She is always happy and active in class', 'Excellent result but you can do better than this', NOW(), NOW()),
(401, 8, 22, 118, 58, 'Blessing missed all the exams for second term', 'Fairly good result. Work harder.', NOW(), NOW()),
(367, 8, 22, 112, 14, 'He is friendly and ready to learn', 'Average performance be serious with your academic', NOW(), NOW()),
(369, 8, 22, 118, 8, 'She is very serious and respectful.', 'Good performance', NOW(), NOW()),
(371, 8, 22, 110, 16, 'She is always cheerful', 'Good results', NOW(), NOW()),
(372, 8, 22, 118, 8, 'She is a gentle giirl but many a time appears weak', 'Good results', NOW(), NOW()),
(373, 8, 22, 122, 4, 'She is a gentle girl and not troublesome', 'Average result', NOW(), NOW()),
(374, 8, 22, 110, 16, 'He is very okay in character display.', 'Poor result put more effort next term', NOW(), NOW()),
(375, 8, 22, 124, 2, 'He is a good boy.', 'Very good result', NOW(), NOW()),
(376, 8, 22, 124, 2, 'She is a gentle girl', 'Very weak result be serious with your academics', NOW(), NOW()),
(377, 8, 22, 124, 2, 'He is always participating well in class', 'Excellent result keep it up', NOW(), NOW()),
(378, 8, 22, 108, 18, 'She is very good', 'Average performance', NOW(), NOW()),
(366, 8, 22, 114, 12, 'He is respectful but losses concentration in class', 'Weak performance be serious with your academic', NOW(), NOW()),
(379, 8, 22, 112, 14, 'She is not hard working', 'Very weak result you can do better than this', NOW(), NOW()),
(365, 8, 22, 122, 4, 'Halimat is a friend to everybody in the class but not organized in keeping her properties safe', 'Good result', NOW(), NOW()),
(380, 8, 22, 118, 8, 'She is very lazy.', 'Weak result try harder next term', NOW(), NOW()),
(381, 8, 22, 116, 10, 'She is very okay in character', 'Good results', NOW(), NOW()),
(364, 8, 22, 114, 12, 'Iremide is respectful and consentrate in class', 'Excellent result keep it up', NOW(), NOW()),
(382, 8, 22, 124, 2, 'Hassan is a quiet boy', 'Weak performance try harder next term', NOW(), NOW()),
(327, 8, 22, 120, 6, 'She is loving and ready to learn', 'Average performance put more effort next term', NOW(), NOW()),
(327, 8, 22, 120, 6, 'She is loving and ready to learn', 'Average performance put more effort next term', NOW(), NOW()),
(383, 8, 22, 124, 2, 'She needs to be careful.', 'Weak performance', NOW(), NOW()),
(384, 8, 22, 122, 4, 'She needs to be more active', 'Average performance', NOW(), NOW()),
(385, 8, 22, 122, 4, 'He argues a lot', 'Good results', NOW(), NOW()),
(386, 8, 22, 122, 4, 'He is a very simple boy', 'Average performance', NOW(), NOW()),
(387, 8, 22, 122, 4, 'She behaves mature.', 'Very good result', NOW(), NOW()),
(388, 8, 22, 124, 2, 'She behaves matured', 'Very good result', NOW(), NOW()),
(389, 8, 22, 124, 2, 'He is always active in class', 'Excellent result keep it up', NOW(), NOW()),
(390, 8, 22, 122, 4, 'He is a gentle boy', 'Good results', NOW(), NOW()),
(391, 8, 22, 122, 4, 'He is a very calm student.', 'Brilliant result', NOW(), NOW()),
(392, 8, 22, 122, 4, 'He is always serious', 'Brilliant result', NOW(), NOW()),
(393, 8, 22, 122, 4, 'She is a well behaved student', 'Average result', NOW(), NOW()),
(394, 8, 22, 122, 4, 'Irenitemi is not always serious', 'Weak performance try harder next term', NOW(), NOW()),
(395, 8, 22, 120, 6, 'He is always talking in class', 'Good result', NOW(), NOW()),
(363, 8, 22, 122, 4, 'She is inquisitive and willing to learn', 'Weak passes put more endeavor into your academic', NOW(), NOW()),
(331, 8, 22, 106, 20, 'He makes friends a lot but lacks full concentration in class', 'Fair performance be serious with your academics', NOW(), NOW()),
(403, 8, 22, 99, 19, 'Hunaidatu plays too much in class', 'Fair attempt. Try harder next term.', NOW(), NOW()),
(404, 8, 22, 118, 0, 'James can be easily distracted in class', 'Poor result. Sit up.', NOW(), NOW()),
(405, 8, 22, 116, 2, 'Havilah is very devoted to his academics', 'Very good academic performance. Keep it up, Havilah.', NOW(), NOW()),
(341, 8, 22, 74, 52, 'She makes friends and inquisitive in class', 'This is not result', NOW(), NOW()),
(406, 8, 22, 116, 2, 'Testimony is serious with his studies', 'Good result. Keep it up.', NOW(), NOW()),
(407, 8, 22, 116, 2, 'Ademola is well behaved in class', 'Good result. Keep it up.', NOW(), NOW()),
(408, 8, 22, 116, 2, 'Rachael is quiet in class but should be more serious with her studies', 'Fairly good result. Try harder.', NOW(), NOW()),
(409, 8, 22, 114, 4, 'Uwem needs to be more serious with his academics', 'Fair attempt. Sit up, Uwem.', NOW(), NOW()),
(410, 8, 22, 118, 0, 'Isaac is very active in class activities', 'Good result. Keep it up.', NOW(), NOW()),
(411, 8, 22, 106, 12, 'Joseph plays alot in class', 'Below average academic performance. Sit up.', NOW(), NOW()),
(412, 8, 22, 110, 8, 'Enoch is very devoted to his studies', 'Very good academic performance. Keep it up, Enoch.', NOW(), NOW()),
(354, 8, 22, 116, 10, 'Richard is eager to learn and active in class', 'Good result', NOW(), NOW()),;
