INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(328, 11, 32, 0, 122, '', '', NOW(), NOW()),
(334, 11, 32, 0, 122, '', '', NOW(), NOW()),
(336, 11, 32, 0, 122, '', '', NOW(), NOW()),
(337, 11, 32, 0, 122, '', '', NOW(), NOW()),
(344, 11, 32, 0, 122, '', '', NOW(), NOW()),
(347, 11, 32, 0, 122, '', '', NOW(), NOW()),
(351, 11, 32, 0, 122, '', '', NOW(), NOW()),
(353, 11, 32, 0, 122, '', '', NOW(), NOW()),
(368, 11, 32, 0, 122, '', '', NOW(), NOW()),
(369, 11, 32, 0, 122, '', '', NOW(), NOW()),
(371, 11, 32, 0, 122, '', '', NOW(), NOW()),
(377, 11, 32, 0, 122, '', '', NOW(), NOW()),
(385, 11, 32, 0, 122, '', '', NOW(), NOW()),
(387, 11, 32, 0, 122, '', '', NOW(), NOW()),
(388, 11, 32, 0, 122, '', '', NOW(), NOW()),
(390, 11, 32, 0, 122, '', '', NOW(), NOW()),
(391, 11, 32, 0, 122, '', '', NOW(), NOW()),
(394, 11, 32, 0, 122, '', '', NOW(), NOW()),
(326, 11, 32, 122, 0, 'Fumilayo is a well behaved student.', 'Very good result. Keep it up!', NOW(), NOW()),
(330, 11, 32, 120, 2, 'She is well behaved.', 'Excellent academic performance. Sofiayat is very hardworking. Keep it up, girl!', NOW(), NOW()),
(331, 11, 32, 120, 2, 'Goodluck is too playful', '', NOW(), NOW()),
(340, 11, 32, 120, 2, 'She is a well behaved student.', 'Good result. Keep it up!', NOW(), NOW()),
(341, 11, 32, 120, 2, 'Favour is a well behaved student.', 'Very good result. Keep it up.', NOW(), NOW()),
(342, 11, 32, 120, 2, 'She is playful.', 'Poor result. Work harder please.', NOW(), NOW()),
(354, 11, 32, 112, 10, 'Richard is a well behaved student.', 'Fairly good result. Work harder still.', NOW(), NOW()),
(355, 11, 32, 113, 9, 'She is a well behaved student.', 'Fairly good result. Sit up', NOW(), NOW()),
(356, 11, 32, 113, 9, 'She is a well behaved student.', 'Fairly good performance. Work harder.', NOW(), NOW()),
(357, 11, 32, 120, 2, 'He is a playful student.', 'Poor attempt. Work harder.', NOW(), NOW()),
(358, 11, 32, 118, 4, 'He is too playful.', 'Very poor performance. Get serious with your studies.', NOW(), NOW()),
(359, 11, 32, 116, 6, 'She is a disciplined student.', 'Fairly good result. Sit up.', NOW(), NOW()),
(360, 11, 32, 120, 2, 'He is a disciplined student.', 'Fairly good result. Try harder', NOW(), NOW()),
(362, 11, 32, 120, 2, 'He is a playful student.', 'Fairly good result. Work harder still.', NOW(), NOW()),
(363, 11, 32, 113, 9, 'He is a playful student.', 'Poor result. Sit up!', NOW(), NOW()),
(366, 11, 32, 110, 12, 'Ramadan is a playful student.', 'Very poor result. Get serious with your studies.', NOW(), NOW()),
(339, 11, 32, 0, 122, '', '', NOW(), NOW()),
(345, 11, 32, 0, 122, '', '', NOW(), NOW()),
(349, 11, 32, 0, 122, '', '', NOW(), NOW()),
(361, 11, 32, 0, 122, '', '', NOW(), NOW()),
(364, 11, 32, 0, 122, '', '', NOW(), NOW()),
(367, 11, 32, 0, 122, '', '', NOW(), NOW()),
(365, 11, 32, 0, 122, '', '', NOW(), NOW()),
(47, 29, 41, 114, 12, 'He exhibits a positive outlook and attitude in the classroom.', 'A very talented young man. The sky is just your starting point', NOW(), NOW()),
(1, 29, 41, 128, 4, 'yes', 'Excellent result keep it up', NOW(), NOW()),
(99, 29, 41, 126, 0, 'Fair result, you need to improve more next term', 'You need to work harder and be focus on your studies', NOW(), NOW()),
(48, 29, 41, 124, 2, 'He is an enthusiastic learner who seems to enjoy school.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(3, 29, 41, 124, 2, 'A fairly good result. You need to work harder next term', 'Good result work harder next term', NOW(), NOW()),
(100, 29, 41, 120, 6, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(64, 29, 41, 118, 8, 'He sets achievable goals with respect to time.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(101, 29, 41, 126, 0, 'Fair result, improve more next term', 'You need to be more hardworking next term', NOW(), NOW()),
(32, 29, 41, 126, 0, 'A very good performance.try more next term', 'Amazing result keep it up', NOW(), NOW()),
(94, 29, 41, 92, 34, 'He takes his classroom jobs seriously and demonstrates responsibility when completing them.', 'Great performance! Promoted to JSS3 class.', NOW(), NOW()),
(102, 29, 41, 126, 0, 'Great Performance, keep soaring high Arnold!', 'Great performance! promoted to JSS2 class.', NOW(), NOW()),
(103, 29, 41, 126, 0, 'Average performance, sit up next time!', 'Average performance! You have to sit up!', NOW(), NOW()),
(81, 29, 41, 114, 12, 'She is always well-prepared for class each day.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(104, 29, 41, 126, 0, 'Great Performance, keep soaring high Balogun!', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(105, 29, 41, 126, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(106, 29, 41, 126, 0, 'A very exceptional and smart student. The sky is just your starting point!', 'Great performance! promoted to JSS2 class.', NOW(), NOW()),
(107, 29, 41, 126, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(108, 29, 41, 126, 0, 'Average performance. He has the ability to do better if only he can put more effort on his academics', 'Fair performance! You have to sit up and focus on your academics.', NOW(), NOW()),
(109, 29, 41, 126, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(110, 29, 41, 124, 2, 'Good performance but you have the capacity to do better', 'Fair performance! promoted to JSS2 class.', NOW(), NOW()),
(111, 29, 41, 126, 0, 'Average performance, sit up next time!', 'This is an average result, you need to sit up!', NOW(), NOW()),
(112, 29, 41, 126, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(113, 29, 41, 120, 6, 'Good performance but there is room for improvement', 'Average performance! promoted to JSS2 class.', NOW(), NOW()),
(114, 29, 41, 126, 0, 'Average performance, sit up next time!', 'Average performance! you need to work harder next term', NOW(), NOW()),
(115, 29, 41, 126, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(116, 29, 41, 120, 6, 'A good result but she has the capacity to do much better.', 'Fair performance! promoted to JSS2 class.', NOW(), NOW()),
(117, 29, 41, 112, 14, 'Fair result, you need to improve more next term', 'There is room for improvement,  work harder next term', NOW(), NOW()),
(118, 29, 41, 126, 0, 'Average performance, sit up next time!', 'Fair performance! promoted to JSS2 class.', NOW(), NOW()),
(119, 29, 41, 124, 6, 'Great Performance, keep soaring high Angel!', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(120, 29, 41, 124, 2, 'Average performance, sit up next time!', 'Average performance! you need to sit up!', NOW(), NOW()),
(121, 29, 41, 126, 0, 'Olajide is an exceptional student. The sky is just her starting point!', 'Great performance! promoted to JSS2 class.', NOW(), NOW()),
(122, 29, 41, 126, 0, 'Average performance, sit up next time!', 'There is room for improvement,  work harder next term', NOW(), NOW()),
(123, 29, 41, 126, 0, 'Good result, there is still room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(124, 29, 41, 126, 0, 'Very good result, keep it up', 'Very good result,  there is room for improvement,  work harder next term', NOW(), NOW()),
(125, 29, 41, 126, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(126, 29, 41, 126, 0, 'Penuel is a very smart girl and with more attention on her academics, the sky will be her starting p', 'Great performance! promoted to JSS2 class.', NOW(), NOW()),
(85, 29, 41, 126, 0, 'She accepts the recommendations of peers and acts on them when appropriate.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(83, 29, 41, 122, 4, 'She is a self-motivated student that loves thriving in her studies.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(87, 29, 41, 118, 8, 'She listens to the comments and ideas of others without interrupting.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(89, 29, 41, 94, 32, 'She is patient and kind when working with her peers who need extra assistance.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(66, 29, 41, 116, 10, 'He works independently in class.', 'Average result, you can perform better! Promoted to JSS3', NOW(), NOW()),
(69, 29, 41, 116, 10, 'He is smart and always willing to participate in class.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(51, 29, 41, 126, 0, 'She takes an active role in discussions.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(50, 29, 41, 124, 2, 'He has an impressive understanding and depth of knowledge about his interests.', 'Keep it up David, the sky is your starting point.', NOW(), NOW()),
(75, 29, 41, 114, 12, 'He asks for clarification when needed.', 'Average performance! You have to work harder next term.', NOW(), NOW()),
(127, 29, 41, 126, 0, 'He is always honest and can be counted on to recount information when asked.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(90, 29, 41, 116, 10, 'She can always be counted on to cooperate with her peers.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(91, 29, 41, 120, 6, 'She is thoughtful and kind in her interactions with others.', 'Great performance! Keep it up! Promoted to JSS3 class.', NOW(), NOW()),
(128, 29, 41, 118, 8, 'He needs to be calm always in interacting with his peers', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(79, 29, 41, 112, 14, 'He tackles classroom assignments, tasks, and group work in an organized manner.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(53, 29, 41, 110, 16, 'She remains an active learner always throughout the school day.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(129, 29, 41, 120, 6, 'He faithfully performs classroom tasks.', 'Fair performance! promoted to JSS3 class', NOW(), NOW()),
(72, 29, 41, 116, 10, 'He is a valued member of the class..', 'Average performance! You can perform better next term. Promoted to JSS3!', NOW(), NOW()),
(93, 29, 41, 126, 0, 'She is trustworthy and can always be counted on to step in and help where needed.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(76, 29, 41, 122, 4, 'He handles disagreements with peers appropriately.', 'Average performance! With more concentration on your academics the sky will be your starting point.', NOW(), NOW()),
(130, 29, 41, 114, 12, 'She does not give up when facing a task that is difficult and always does her best', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(131, 29, 41, 114, 12, 'She perseveres when faced with difficulty by asking questions and trying her best', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(62, 29, 41, 122, 4, 'He avoids careless errors through paying attention to details.', 'Good result, you can do better! Promoted to JSS3', NOW(), NOW()),
(34, 29, 41, 126, 0, 'A fairly good results but you need to pay more attention to your studies', 'Good result work harder next term', NOW(), NOW()),;
