INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(36, 29, 41, 126, 0, 'A very good performance.try more next term', 'Excellent performance keep it up', NOW(), NOW()),
(38, 29, 41, 126, 0, 'A very good result perform more better next term', 'Amazing result keep it up', NOW(), NOW()),
(41, 29, 41, 126, 0, 'A very good performance try harder next term', 'Good result keep it up', NOW(), NOW()),
(42, 29, 41, 120, 6, 'A very good result work harder on your weak subject', 'Good result keep it up', NOW(), NOW()),
(43, 29, 41, 114, 12, 'A good performance try and work harder next term', 'Good result keep it up', NOW(), NOW()),
(44, 29, 41, 116, 10, 'A very good performance,work harder on ur weak subject', 'Amazing keep it up', NOW(), NOW()),
(45, 29, 41, 118, 8, 'A very good performance need to try more better next term', 'Amazing result keep it up', NOW(), NOW()),
(46, 29, 41, 126, 0, 'A very good performance. keep it up', 'Amazing result keep it up', NOW(), NOW()),
(52, 29, 41, 126, 0, 'A very good performance.try more next term', 'Excellent performance keep it up', NOW(), NOW()),
(54, 29, 41, 126, 0, 'A very good performance. keep it up', 'Excellent performance keep it up', NOW(), NOW()),
(56, 29, 41, 126, 0, 'A very good performance keep it up', 'Amazing result keep it up', NOW(), NOW()),
(95, 29, 41, 126, 0, 'A very good performance.try more next term', 'Good performance try harder next term', NOW(), NOW()),
(132, 29, 41, 126, 0, 'A very good performance.try more next term', 'Nice result keep it up', NOW(), NOW()),
(133, 29, 41, 124, 2, 'A fairly good results but you need to pay more attention to your studies', 'There is a room for improvement.you have to studies hard next term', NOW(), NOW()),
(39, 29, 41, 90, 36, 'A good performance try and work harder next term', 'Kanyinsola, you need to work harder and be more focused on your academics', NOW(), NOW()),
(10, 29, 41, 122, 6, 'He cooperates consistently with the teacher and other students.', 'Great performance Ronaldo. Keep it up! Promoted to SS2', NOW(), NOW()),
(13, 29, 41, 110, 18, 'He responds appropriately when corrected.', 'Average performance! With more concentration on your academics you will perform better.', NOW(), NOW()),
(15, 29, 41, 114, 14, 'She resists the urge to be distracted by other students.', 'Average performance! With more concentration on your academics you can perform better.', NOW(), NOW()),
(17, 29, 41, 126, 0, 'Good performance. Royhan is very intentional about learning but needs to devote more time to studyin', 'Good performance but you can perform better. Promoted to SS2 class.', NOW(), NOW()),
(19, 29, 41, 118, 10, 'She is thoughtful in interactions with others.', 'Great performance! Keep it up !', NOW(), NOW()),
(21, 29, 41, 126, 0, 'A good performance, keep it up Hephzibah. The sky is just your starting point.', 'Amazing result,  do not lose focus...keep it up', NOW(), NOW()),
(134, 29, 41, 120, 8, 'She takes her classroom jobs seriously and demonstrates responsibility when completing them.', 'Average performance! With more concentration on your academics you can perform better.', NOW(), NOW()),
(135, 29, 41, 118, 10, 'He is always honest and can be counted on to recount information when asked.', 'Good performance! With more attention on your academics you can perform better.', NOW(), NOW()),
(22, 29, 41, 115, 13, 'He does not give up when facing a task that is difficult and always does his best.', 'Good result but you can do better. Promoted to SS3.', NOW(), NOW()),
(24, 29, 41, 110, 16, 'Fairly good result, with more focus on your academics you can perform better', 'Good result,  you need to work harder next term', NOW(), NOW()),
(26, 29, 41, 116, 12, 'She can always be counted on to cooperate with her peers.', 'Good result. Keep it up! Promoted to SS3.', NOW(), NOW()),
(29, 29, 41, 120, 8, 'She is always enthusiastic when completing her work.', 'Good result, keep it up. Promoted to SS3.', NOW(), NOW()),
(94, 29, 42, 92, 34, 'He takes his classroom jobs seriously and demonstrates responsibility when completing them.', 'Great performance! Promoted to JSS3 class.', NOW(), NOW()),
(137, 29, 42, 112, 14, 'She is honest and trustworthy in dealings with others.', 'Fair performance! Promoted to JSS3 class.', NOW(), NOW()),
(138, 29, 42, 122, 4, 'She resists the urge to be distracted by other students always.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(136, 29, 42, 123, 3, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(53, 29, 42, 110, 16, 'She remains an active learner always throughout the school day.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(40, 29, 42, 122, 4, 'Good performance but there is room for improvement', 'Good performance but you can do better next term', NOW(), NOW()),
(64, 29, 42, 118, 8, 'He sets achievable goals with respect to time.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(81, 29, 42, 114, 12, 'She is always well-prepared for class each day.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(85, 29, 42, 126, 0, 'She accepts the recommendations of peers and acts on them when appropriate.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(83, 29, 42, 122, 4, 'She is a self-motivated student that loves thriving in her studies.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(87, 29, 42, 118, 8, 'She listens to the comments and ideas of others without interrupting.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(89, 29, 42, 94, 32, 'She is patient and kind when working with her peers who need extra assistance.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(48, 29, 42, 124, 2, 'He is an enthusiastic learner who seems to enjoy school.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(66, 29, 42, 116, 10, 'He works independently in class.', 'Average result, you can perform better! Promoted to JSS3', NOW(), NOW()),
(69, 29, 42, 116, 10, 'He is smart and always willing to participate in class.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(51, 29, 42, 126, 0, 'She takes an active role in discussions.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(50, 29, 42, 124, 2, 'He has an impressive understanding and depth of knowledge about his interests.', 'Keep it up David, the sky is your starting point.', NOW(), NOW()),
(47, 29, 42, 114, 12, 'He exhibits a positive outlook and attitude in the classroom.', 'A very talented young man. The sky is just your starting point', NOW(), NOW()),
(22, 29, 42, 115, 13, 'He does not give up when facing a task that is difficult and always does his best.', 'Good result but you can do better. Promoted to SS3.', NOW(), NOW()),
(62, 29, 42, 122, 4, 'He avoids careless errors through paying attention to details.', 'Good result, you can do better! Promoted to JSS3', NOW(), NOW()),
(24, 29, 42, 110, 16, '', '', NOW(), NOW()),
(127, 29, 42, 126, 0, 'He is always honest and can be counted on to recount information when asked.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(76, 29, 42, 122, 4, 'He handles disagreements with peers appropriately.', 'Average performance! With more concentration on your academics the sky will be your starting point.', NOW(), NOW()),
(26, 29, 42, 116, 12, 'She can always be counted on to cooperate with her peers.', 'Good result. Keep it up! Promoted to SS3.', NOW(), NOW()),
(29, 29, 42, 120, 8, 'She is always enthusiastic when completing her work.', 'Good result, keep it up. Promoted to SS3.', NOW(), NOW()),
(75, 29, 42, 114, 12, 'He asks for clarification when needed.', 'Average performance! You have to work harder next term.', NOW(), NOW()),
(92, 29, 42, 120, 6, '', '', NOW(), NOW()),
(90, 29, 42, 116, 10, 'She can always be counted on to cooperate with her peers.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(91, 29, 42, 120, 6, 'She is thoughtful and kind in her interactions with others.', 'Great performance! Keep it up! Promoted to JSS3 class.', NOW(), NOW()),
(93, 29, 42, 126, 0, 'She is trustworthy and can always be counted on to step in and help where needed.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(128, 29, 42, 118, 8, 'He needs to be calm always in interacting with his peers', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(130, 29, 42, 114, 12, 'She does not give up when facing a task that is difficult and always does her best', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(131, 29, 42, 114, 12, 'She perseveres when faced with difficulty by asking questions and trying her best', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(79, 29, 42, 112, 14, 'He tackles classroom assignments, tasks, and group work in an organized manner.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(129, 29, 42, 120, 6, 'He faithfully performs classroom tasks.', 'Fair performance! promoted to JSS3 class', NOW(), NOW()),
(72, 29, 42, 116, 10, 'He is a valued member of the class..', 'Average performance! You can perform better next term. Promoted to JSS3!', NOW(), NOW()),
(1, 29, 43, 128, 0, 'yes', '', NOW(), NOW()),
(47, 29, 43, 0, 0, 'He exhibits a positive outlook and attitude in the classroom.', 'A very talented young man. The sky is just your starting point', NOW(), NOW()),
(48, 29, 43, 0, 0, 'He is an enthusiastic learner who seems to enjoy school.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(50, 29, 43, 0, 0, 'He has an impressive understanding and depth of knowledge about his interests.', 'Keep it up David, the sky is your starting point.', NOW(), NOW()),
(51, 29, 43, 0, 0, 'She takes an active role in discussions.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(53, 29, 43, 0, 0, 'She remains an active learner always throughout the school day.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(62, 29, 43, 0, 0, 'He avoids careless errors through paying attention to details.', 'Good result, you can do better! Promoted to JSS3', NOW(), NOW()),
(64, 29, 43, 0, 0, 'He sets achievable goals with respect to time.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(66, 29, 43, 0, 0, 'He works independently in class.', 'Average result, you can perform better! Promoted to JSS3', NOW(), NOW()),
(69, 29, 43, 0, 0, 'He is smart and always willing to participate in class.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(72, 29, 43, 0, 0, 'He is a valued member of the class..', 'Average performance! You can perform better next term. Promoted to JSS3!', NOW(), NOW()),
(75, 29, 43, 0, 0, 'He asks for clarification when needed.', 'Average performance! You have to work harder next term.', NOW(), NOW()),
(76, 29, 43, 0, 0, 'He handles disagreements with peers appropriately.', 'Average performance! With more concentration on your academics the sky will be your starting point.', NOW(), NOW()),
(79, 29, 43, 0, 0, 'He tackles classroom assignments, tasks, and group work in an organized manner.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(81, 29, 43, 0, 0, 'She is always well-prepared for class each day.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(83, 29, 43, 0, 0, 'She is a self-motivated student that loves thriving in her studies.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(85, 29, 43, 0, 0, 'She accepts the recommendations of peers and acts on them when appropriate.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(87, 29, 43, 0, 0, 'She listens to the comments and ideas of others without interrupting.', 'Great result, keep it up! Promoted to JSS3', NOW(), NOW()),
(89, 29, 43, 0, 0, 'She is patient and kind when working with her peers who need extra assistance.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(90, 29, 43, 0, 0, 'She can always be counted on to cooperate with her peers.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(91, 29, 43, 0, 0, 'She is thoughtful and kind in her interactions with others.', 'Great performance! Keep it up! Promoted to JSS3 class.', NOW(), NOW()),
(93, 29, 43, 0, 0, 'She is trustworthy and can always be counted on to step in and help where needed.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(94, 29, 43, 0, 0, 'He takes his classroom jobs seriously and demonstrates responsibility when completing them.', 'Great performance! Promoted to JSS3 class.', NOW(), NOW()),
(127, 29, 43, 0, 0, 'He is always honest and can be counted on to recount information when asked.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(128, 29, 43, 0, 0, 'He needs to be calm always in interacting with his peers', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(129, 29, 43, 0, 0, 'He faithfully performs classroom tasks.', 'Fair performance! promoted to JSS3 class', NOW(), NOW()),
(130, 29, 43, 0, 0, 'She does not give up when facing a task that is difficult and always does her best', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(131, 29, 43, 0, 0, 'She perseveres when faced with difficulty by asking questions and trying her best', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(137, 29, 43, 0, 0, 'She is honest and trustworthy in dealings with others.', 'Fair performance! Promoted to JSS3 class.', NOW(), NOW()),
(138, 29, 43, 0, 0, 'She resists the urge to be distracted by other students always.', 'Good performance! promoted to JSS3 class', NOW(), NOW()),
(126, 29, 43, 0, 0, 'Penuel is a very smart girl and with more attention on her academics, the sky will be her starting p', 'Great performance! promoted to JSS2 class.', NOW(), NOW()),
(22, 29, 43, 115, 13, 'He does not give up when facing a task that is difficult and always does his best.', 'Good result but you can do better. Promoted to SS3.', NOW(), NOW()),
(26, 29, 43, 116, 12, 'She can always be counted on to cooperate with her peers.', 'Good result. Keep it up! Promoted to SS3.', NOW(), NOW()),
(29, 29, 43, 120, 8, 'She is always enthusiastic when completing her work.', 'Good result, keep it up. Promoted to SS3.', NOW(), NOW()),
(10, 29, 43, 122, 6, 'He cooperates consistently with the teacher and other students.', 'Great performance Ronaldo. Keep it up! Promoted to SS2', NOW(), NOW()),
(13, 29, 43, 110, 18, 'He responds appropriately when corrected.', 'Average performance! With more concentration on your academics you will perform better.', NOW(), NOW()),
(15, 29, 43, 114, 14, 'She resists the urge to be distracted by other students.', 'Average performance! With more concentration on your academics you can perform better.', NOW(), NOW()),;
