INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(350, 9, 26, 108, 8, 'He faithfully performs classroom task', 'Good results', NOW(), NOW()),
(353, 9, 26, 94, 22, 'He should learn how to show respect to both teachers and students', 'Average performance', NOW(), NOW()),
(360, 9, 26, 114, 2, 'Heâ€™s always active and ready to learn more', 'Good performance', NOW(), NOW()),
(422, 9, 26, 96, 20, 'Shola really need to be serious with his studies.', '', NOW(), NOW()),
(326, 9, 27, 102, 0, 'Very impressive result keep it up mercy.', 'Good results promoted to jss3', NOW(), NOW()),
(327, 9, 27, 102, 0, 'Sheâ€™s a good girl and well behaved', 'Good results promoted to jss3', NOW(), NOW()),
(330, 9, 27, 102, 0, 'Sheâ€™s well disciplined and intelligent.', 'Excellent performance keep it up promoted to jss3', NOW(), NOW()),
(339, 9, 27, 102, 0, 'Well behaved and and intelligent girl.l', 'Good results promoted to jss3', NOW(), NOW()),
(340, 9, 27, 102, 0, 'Sheâ€™s a good girl and well behaved', 'Good results promoted to jss3', NOW(), NOW()),
(341, 9, 27, 102, 0, 'Sheâ€™s a good girl and well mannered.', 'Good results keep it up promoted to jss3', NOW(), NOW()),
(357, 9, 27, 100, 2, 'Sheâ€™s a good girl and well behaved in class.', 'Average performance sit up promoted to jss3', NOW(), NOW()),
(342, 9, 27, 102, 0, 'Favourâ€™s a quiet girl in the class but also need to put more effort academically.', 'Average performance sit up promoted to jss3', NOW(), NOW()),
(355, 9, 27, 102, 0, 'Sheâ€™s a good girl and well behaved', 'Average performance sit up promoted to jss3', NOW(), NOW()),
(354, 9, 27, 100, 2, 'Heâ€™s well reserved and well mannered.', 'Good results promoted to jss3', NOW(), NOW()),
(356, 9, 27, 98, 4, 'Sheâ€™s a good girl and well behaved', 'Good results promoted to jss3', NOW(), NOW()),
(358, 9, 27, 96, 6, 'Heâ€™s always active but need more seriousness to academics.', 'Fair results sit up promoted to jss3', NOW(), NOW()),
(359, 9, 27, 90, 12, 'Sheâ€™s a good girl and ready to learn.', 'Average performance sit up promoted to jss3', NOW(), NOW()),
(360, 9, 27, 90, 12, 'Heâ€™s always active and ready to learn more', 'Good results but you can do better than this next term promoted to jss3', NOW(), NOW()),
(361, 9, 27, 98, 12, 'Heâ€™s a good boy and ready to learn more', 'Fair results sit up promoted to jss3', NOW(), NOW()),
(362, 9, 27, 96, 6, 'Heâ€™s always active and ready to learn more', 'Good results promoted to jss3', NOW(), NOW()),
(363, 9, 27, 100, 2, 'Sheâ€™s a good girl,well behaved and also improving academically.', 'Average performance sit up promoted to jss3', NOW(), NOW()),
(366, 9, 27, 98, 4, 'Heâ€™s a good boy but needs more attention.', 'Fair results sit up promoted to jss3', NOW(), NOW()),
(367, 9, 27, 98, 4, 'Heâ€™s always active and ready to learn more', 'Good results promoted to jss3', NOW(), NOW()),
(397, 9, 27, 100, 2, 'Obiita is well behaved and always ready to learn.', 'Excellent academic performance.  Keep it up.  Promoted.', NOW(), NOW()),
(400, 9, 27, 100, 2, 'Roland is calm and well behaved in class.', 'Good result.  Well done. Promoted to SS 3', NOW(), NOW()),
(370, 9, 27, 96, 6, 'Juliana is well behaved student.', 'Good result. Sit up still.  Promoted to SS2', NOW(), NOW()),
(408, 9, 27, 100, 2, 'Rachel is calm and very attentive in class.', 'Good result.  Keep it up. Promoted to SS 3.', NOW(), NOW()),
(399, 9, 27, 98, 4, 'David is smart and friendly in class .', 'Good result.  Try harder still.  Promoted to SS 3.', NOW(), NOW()),
(401, 9, 27, 98, 4, 'Blessing is friendly and active in class.', 'Good result.  Try harder still.  Promoted to SS3', NOW(), NOW()),
(402, 9, 27, 100, 2, 'Victoria is active in class and always ready to learn', 'Very good academic report.  Keep it up, Vicky. Promoted to SS 3', NOW(), NOW()),
(404, 9, 27, 96, 6, 'James is calm and well behaved.He needs to focus more on his studies', 'Fair attempt.  Sit up still.  Promoted to SS 3.', NOW(), NOW()),
(405, 9, 27, 100, 2, 'Havilah is smart and very active in class.', 'Excellent! Please, do not relent, Havilah. Promoted to SS 3.', NOW(), NOW()),
(406, 9, 27, 102, 0, 'Testimony is very attentive in class and respectful', 'Good result.  However, this is not your best.', NOW(), NOW()),
(407, 9, 27, 100, 2, 'Ademola is calm and well behaved in class.', 'Very good result.  Keep it up.  Promoted to SS 3.', NOW(), NOW()),
(410, 9, 27, 100, 2, 'Victory is smart and very active in class', 'Very good result.  Keep it up. Promoted to SS3.', NOW(), NOW()),
(411, 9, 27, 100, 2, 'Joseph is very friendly and smart. He needs to pay more attention to his studies.', 'Good result.  Keep it up.  Promoted to SS 3', NOW(), NOW()),
(412, 9, 27, 100, 2, 'Enoch is intelligent and well behaved in class.', 'Excellent academic performance.  Please, do not relent.  Promoted to SS 3.', NOW(), NOW()),
(413, 9, 27, 102, 0, 'Emmanuel is well behaved and always ready to learn.', 'Very good result.  Keep it up.  Promoted to SS 3.', NOW(), NOW()),
(414, 9, 27, 98, 4, 'David is calm and well behaved in class.', 'Fair attempt.  Sit up.  Promoted to SS 3.', NOW(), NOW()),
(415, 9, 27, 100, 2, 'Keji is hardworking and very attentive in class.', 'Very good academic report.  Keep it up, Keji.', NOW(), NOW()),
(417, 9, 27, 100, 2, 'Lekan is very smart and active in class.', 'Fair attempt.  Sit up. Promoted!', NOW(), NOW()),
(418, 9, 27, 100, 2, 'Mercy is well behaved and participates well in class.', 'Very good academic performance.  Keep it up. Promoted.', NOW(), NOW()),
(419, 9, 27, 100, 2, 'Esther is well behaved and participates well in class.', 'Good result.  Keep it up.  Promoted to SS 3.', NOW(), NOW()),
(420, 9, 27, 100, 2, 'Anjola is a good girl and she always ready to learn', 'Good result. Keep it up', NOW(), NOW()),
(421, 9, 27, 90, 12, 'Samuel needs to be more serious with his studies', 'Fair attempt.  Sit up.', NOW(), NOW()),
(423, 9, 27, 100, 2, 'Ramadan is well behaved and participates well in class.', 'Good result.  Keep it up. Promoted!', NOW(), NOW()),
(425, 9, 27, 100, 2, 'Firdausi is calm,respectful and attentive in class', 'Good result. Keep it up.  Promoted!', NOW(), NOW()),
(426, 9, 27, 98, 4, 'Ademola is calm and well behaved in class.', 'Fair attempt.  Sit up. Promoted!', NOW(), NOW()),
(427, 9, 27, 96, 6, 'Abdullahi is calm and well behaved in class.', 'Fair attempt.  Sit up.', NOW(), NOW()),
(428, 9, 27, 90, 12, 'Abideen is playful and needs to concentrate more in his studies.', 'Fair attempt.  Sit up.', NOW(), NOW()),
(422, 9, 27, 90, 12, 'Shola really need to be serious with his studies.', 'Poor result.  Sit up.', NOW(), NOW()),
(373, 9, 27, 102, 0, 'Hussenait is a well behaved in the classroom', 'Good result, Keep it up. Promoted!', NOW(), NOW()),
(376, 9, 27, 92, 10, 'Oyinkasola is well behaved in the class.', 'Poor result.  Sit up.  Promoted', NOW(), NOW()),
(389, 9, 27, 100, 2, 'Abideen is well behaved in the class.', 'Excellent academic performance.  Keep it up, Abideen. Promoted to SS2', NOW(), NOW()),
(384, 9, 27, 95, 7, 'Saratu should learn to be more to be more respectful to her teachers.', 'Fair attempt.  Try harder.  Promoted', NOW(), NOW()),
(374, 9, 27, 96, 6, 'Ezekiel is too playful in the classroom.', 'Fair attempt. Sit up. Promoted!', NOW(), NOW()),
(378, 9, 27, 86, 16, 'Adeola behaves well in the class.', 'Fair attempt.  Sit up', NOW(), NOW()),
(379, 9, 27, 90, 12, 'Nifemi behaves well in the class.', 'Poor result.  Sit up.', NOW(), NOW()),
(380, 9, 27, 100, 2, 'Grace is easily distracted by her friends during lessons.', 'Poor result.  Try harder.', NOW(), NOW()),
(381, 9, 27, 102, 0, 'Faith is a well behaved student', 'Good result.  Try harder still.  Promoted to SS2', NOW(), NOW()),
(382, 9, 27, 102, 0, '', 'Fair attempt.  Promoted', NOW(), NOW()),
(383, 9, 27, 98, 4, 'Daniella behaves well in the class.', 'Good result.  Try harder still.  Promoted!', NOW(), NOW()),
(386, 9, 27, 100, 2, 'Uche is a well behaved student.', 'Good result.  However, there is room for improvement.  Promoted!', NOW(), NOW()),
(392, 9, 27, 100, 2, 'John is a well behaved student.', 'Very Good result.  Keep it up, John.  Promoted to SS2.', NOW(), NOW()),
(395, 9, 27, 102, 2, 'Victor can be very troublesome in the class.', 'Fair attempt.  Sit up.  Promoted', NOW(), NOW()),
(331, 9, 27, 100, 2, 'Jonathan is a good boy but need more attention to school works.', 'Fair results sit up promoted to jss3', NOW(), NOW()),
(329, 10, 28, 124, 2, 'Semilore is well behaved in the class.', 'Poor attempt. Sit up, please.', NOW(), NOW()),
(333, 10, 28, 126, 0, 'Esther behaves well in the class.', 'Good result. Try harder, still.', NOW(), NOW()),
(334, 10, 28, 92, 34, 'Esther is very quiet in the class.', 'Poor result. Sit up.', NOW(), NOW()),
(419, 10, 28, 120, 6, 'Esther is active and dedicated to her work', 'Good performance', NOW(), NOW()),
(396, 10, 28, 124, 2, 'Divine is ready to learn and diligent in character', 'Good performance', NOW(), NOW()),
(423, 10, 28, 126, 0, 'Ramadan needs to focus more on his studies', 'Average performance', NOW(), NOW()),
(429, 10, 28, 126, 0, 'He needs to pay more attention in class', '', NOW(), NOW()),
(400, 10, 28, 124, 2, 'Roland needs to put in more effort for a better result', 'Average performance', NOW(), NOW()),
(397, 10, 28, 118, 8, 'She is active in class and hardworking', 'Excellent result', NOW(), NOW()),
(398, 10, 28, 124, 2, 'Victor is attentive in class and hardworking', 'Average performance', NOW(), NOW()),
(426, 10, 28, 122, 4, 'He needs to put in more effort for a better result next term', 'Average performance', NOW(), NOW()),
(407, 10, 28, 120, 6, 'He has a good communication skills with his colleagues', 'Average performance', NOW(), NOW()),
(413, 10, 28, 112, 14, 'He is always neat and respectful', 'Average performance', NOW(), NOW()),
(412, 10, 28, 114, 12, 'Enoch is studious and hardworking', 'Excellent result', NOW(), NOW()),
(414, 10, 28, 108, 18, 'He needs to be regular in school and punctual', 'Failed', NOW(), NOW()),
(417, 10, 28, 118, 8, 'He needs to pay more attention in class and play less', 'Average performance', NOW(), NOW()),
(399, 10, 28, 112, 14, 'He needs to put in more effort for a better result next term', 'Fair results', NOW(), NOW()),
(418, 10, 28, 110, 16, 'She is active in class and hardworking', 'Good performance', NOW(), NOW()),
(427, 10, 28, 122, 4, 'He needs to concentrate more on his studies', 'Fair results', NOW(), NOW()),
(420, 10, 28, 98, 28, 'She needs to be regular in class', 'Average performance', NOW(), NOW()),
(405, 10, 28, 106, 20, 'Havilah is studious and hardworking', 'Good results', NOW(), NOW()),
(338, 10, 28, 126, 0, 'Ochuko is a well behaved student.', 'You can do better than this, Ochuko. I am rooting for you.', NOW(), NOW()),
(343, 10, 28, 120, 6, 'Victory is a very responsible and well behaved student.', 'An Excellent result. Keep it up, Imarhia', NOW(), NOW()),
(344, 10, 28, 108, 18, 'Mubarak is very playful in class. He should learn to stay focused during class lessons.', 'Poor result, sit up.', NOW(), NOW()),
(346, 10, 28, 114, 12, 'Victory behaves well in the class.', 'Poor attempt. Sit up', NOW(), NOW()),
(348, 10, 28, 108, 18, 'Mubarak is very playful in the class.', 'Poor attempt. Sit up.', NOW(), NOW()),
(392, 10, 28, 126, 0, 'Very Good. Keep it up.', 'Excellent performance', NOW(), NOW()),
(349, 10, 28, 124, 2, 'Feranmi is a well behaved student. He is also very obedient and respectful to his teachers.', 'Good result. Keep it up.', NOW(), NOW()),
(350, 10, 28, 124, 2, 'Meshach is well behaved in the class but can be sometimes very playful.', 'Fair attempt. Sit up.', NOW(), NOW()),
(351, 10, 28, 126, 0, 'Richard is well behaved in the class.', 'Fair attempt. Sit up!', NOW(), NOW()),
(352, 10, 28, 112, 14, 'Queen is a well behaved student. She never gives trouble in the class.', 'Fair attempt. Sit up.', NOW(), NOW()),
(370, 10, 28, 116, 10, 'Put more effort please.', 'Average performance', NOW(), NOW()),
(372, 10, 28, 126, 0, 'Improve to a stronger performance.', 'Average performance', NOW(), NOW()),
(373, 10, 28, 126, 0, 'Put more effort.', 'Average performance', NOW(), NOW()),;
