INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(435, 8, 23, 106, 12, 'Destiny is friendly and relates well with his peers,but needs to study more', 'Poor attempt. Sit up!', NOW(), NOW()),
(329, 8, 23, 112, 6, 'Always ready to learn.', 'Average results please sit up', NOW(), NOW()),
(332, 8, 23, 116, 2, 'Always put in her best.', 'Good performance try harder', NOW(), NOW()),
(334, 8, 23, 102, 16, 'Her learning attitude is poor.', 'Very poor result', NOW(), NOW()),
(336, 8, 23, 112, 6, 'Improving day by day.', 'Average performance sit up', NOW(), NOW()),
(337, 8, 23, 100, 18, 'Not regular in school.', 'Fair results be serious with your academics', NOW(), NOW()),
(338, 8, 23, 118, 0, 'Well mannered girl.', 'Good performance you can do better than this', NOW(), NOW()),
(343, 8, 23, 116, 2, 'Best in all subjects,but you need to work on your temperament.', 'Excellent performance the sky is your limit keep it up', NOW(), NOW()),
(344, 8, 23, 118, 0, 'His attitude towards learning is poor', 'Poor result sit up', NOW(), NOW()),
(346, 8, 23, 108, 10, 'Victory with a wonderful smile .', 'Good performance but there is for improvement', NOW(), NOW()),
(347, 8, 23, 108, 10, 'Odion Miracle loose concentration in class.', 'Average performance sit up', NOW(), NOW()),
(348, 8, 23, 108, 10, 'Too playful but easily corrected .', 'Fair results try harder next term', NOW(), NOW()),
(349, 8, 23, 118, 0, 'Positive minded', 'Good performance keep it up', NOW(), NOW()),
(350, 8, 23, 116, 2, 'Positive minded', 'Good performance', NOW(), NOW()),
(351, 8, 23, 114, 4, 'Always ready to learn.', 'Good performance although there is room for improvement', NOW(), NOW()),
(352, 8, 23, 114, 4, 'Well behaved girl', 'Good performance', NOW(), NOW()),
(353, 8, 23, 102, 16, 'Well mannered boy', 'Average performance sit up', NOW(), NOW()),
(437, 8, 23, 118, 0, 'She is active in class and always ready to learn.', 'Brilliant result. Keep it up.', NOW(), NOW()),
(438, 8, 23, 102, 16, 'Opeyemi is calm, but he needs to read and study more for better results.', 'Fair attempt. Sit up', NOW(), NOW()),
(354, 8, 23, 104, 14, 'He is calm and respectful', 'Good performance but there is room for improvement', NOW(), NOW()),
(355, 8, 23, 112, 6, 'Esther is jovial,friendly and inquisitive in class', 'Average performance sit up', NOW(), NOW()),
(356, 8, 23, 118, 0, 'She is well behaved and respond to class activities quickly', 'Good results', NOW(), NOW()),
(357, 8, 23, 108, 10, 'She is a lover of all and inquisitive in class', 'Average performance sit up', NOW(), NOW()),
(358, 8, 23, 118, 0, 'He is well behaved but lost concentration most times', 'Fair results be serious with your academics', NOW(), NOW()),
(359, 8, 23, 116, 2, 'She is always eager to learn and loves to be corrected', 'Average performance kindly sit up', NOW(), NOW()),
(360, 8, 23, 118, 0, 'He plays a lot but focused and determined', 'Very good results keep it up', NOW(), NOW()),
(361, 8, 23, 116, 2, 'He is well behaved and inquisitive in class', 'Average performance  sit up', NOW(), NOW()),
(362, 8, 23, 114, 4, 'He is willing to learn and friendly', 'Average performance there is room for improvement', NOW(), NOW()),
(367, 8, 23, 114, 4, 'He is well behaved and ready to learn', 'Average performance sit up', NOW(), NOW()),
(366, 8, 23, 118, 0, 'He is willing to learn but lacks concentration in class', 'Very poor result kindly sit up', NOW(), NOW()),
(365, 8, 23, 118, 0, 'She is ready to learn but lacks concentration in her class activities', 'Average performance you can do better than this', NOW(), NOW()),
(364, 8, 23, 116, 2, 'He is intelligent and always willing to learn', 'Very good performance keep it up', NOW(), NOW()),
(363, 8, 23, 114, 4, 'She is well behaved and ready to learn', 'Fair results you better sit up', NOW(), NOW()),
(446, 8, 23, 112, 6, 'Khalid is humble and very friendly in class. He needs to avoid distractions in his studies', 'Fairly good result. You have the potential to do better. So brace up and unleash the genius in you.', NOW(), NOW()),
(345, 8, 23, 90, 28, '', 'Average performance sit up', NOW(), NOW()),
(328, 8, 39, 106, 2, 'She is committed to doing her best', 'Excellent academic performance. Keep it up, Yesira.', NOW(), NOW()),
(351, 8, 39, 106, 2, 'He is quite active in class', 'Good result. Keep it up!', NOW(), NOW()),
(349, 8, 39, 108, 0, 'He is committed to doing his best', 'Very good result. Keep it up', NOW(), NOW()),
(348, 8, 39, 90, 18, 'He needs to be more serious with his studies', 'Fair result. Try harder!', NOW(), NOW()),
(334, 8, 39, 98, 10, 'She should be more open and interactive to teachers and students.', 'Poor attempt. Sit up', NOW(), NOW()),
(344, 8, 39, 102, 6, 'He needs to build reading vocabulary', 'Fair attempt. Sit up!', NOW(), NOW()),
(335, 8, 39, 96, 12, 'Improving day by day.', 'Fair attempt. Sit up!', NOW(), NOW()),
(336, 8, 39, 96, 12, 'Putting more effort in your studies is required', 'Average academic performance. Sit up!', NOW(), NOW()),
(338, 8, 39, 108, 0, 'She is more serious than before', 'Good result. Keep it up.', NOW(), NOW()),
(343, 8, 39, 104, 4, 'Her progress is consistent', 'Excellent academic performance. Victory is very hard-working. Please, do not relent.', NOW(), NOW()),
(350, 8, 39, 104, 4, 'He shows respect to teachers and students', 'Good result. Keep it up', NOW(), NOW()),
(346, 8, 39, 102, 6, 'Needs to pay more attention to studies', 'Good result. Try harder still.', NOW(), NOW()),
(352, 8, 39, 102, 6, 'She is very respectful', 'Good result. Keep it', NOW(), NOW()),
(347, 8, 39, 102, 6, 'He is a very smart student but needs to be serious', 'Fair attempt. Sit up!', NOW(), NOW()),
(337, 8, 39, 88, 20, 'More attention should be devoted to reading and writing', 'Fair attempt. Sit up.', NOW(), NOW()),
(353, 8, 39, 16, 92, 'Positive attitude towards learning is needed', 'Average result. Sit up.', NOW(), NOW()),
(396, 8, 39, 104, 4, 'Divine is  a well behaved student', 'Good performance promoted to ss2', NOW(), NOW()),
(397, 8, 39, 106, 2, 'Obita is a very serious student', 'Excellent result keep it up promoted to ss2', NOW(), NOW()),
(398, 8, 39, 106, 2, 'Victor is well behaved in class', 'Good performance promoted to ss2', NOW(), NOW()),
(399, 8, 39, 108, 0, 'David is well-behaved in class', 'Fair results sit up promoted to ss2', NOW(), NOW()),
(400, 8, 39, 108, 0, 'Roland plays alot in class', 'Fair results sit up promoted to ss2', NOW(), NOW()),
(401, 8, 39, 95, 13, 'Blessing is very quiet in class', 'Fair results sit up promoted to ss2', NOW(), NOW()),
(402, 8, 39, 108, 0, 'Victoria is a well behaved student', 'Good performance promoted to ss2', NOW(), NOW()),
(339, 8, 39, 98, 10, 'Mercy is intelligent and has good relationship with people around her', 'Evidence of hardworking. Mercy is very diligent. Keep it up, girl!', NOW(), NOW()),
(403, 8, 39, 90, 18, 'Hunaidatu plays alot in class', 'Average performance sit up promoted to ss2', NOW(), NOW()),
(404, 8, 39, 108, 0, 'James is too playful in class', 'Fair performance try harder next term promoted to ss2', NOW(), NOW()),
(405, 8, 39, 92, 16, 'Havilah is  a well behaved student and also very seroyud with his studies', 'Excellent performance keep it up promoted to ss2', NOW(), NOW()),
(406, 8, 39, 106, 2, 'Testimony is well behaved, although he can become too playful sometimes', 'Good performance but you can do better than this promoted ss2', NOW(), NOW()),
(431, 8, 39, 108, 0, 'Rafiat is a well behaved and diligent student. Keep it up girl.', 'Good performance promoted to ss3 class', NOW(), NOW()),
(407, 8, 39, 108, 0, 'Ademola is a well behaved student', 'Good performance promoted to ss2', NOW(), NOW()),
(432, 8, 39, 108, 0, 'Ope is easily distracted and this affects her concentration. She needs to avoid distractions for bet', 'Weak performance promoted to ss3 class', NOW(), NOW()),
(340, 8, 39, 106, 2, 'She is friendly and inquisitive in class', 'Average academic performance.Try harder still.', NOW(), NOW()),
(437, 8, 39, 106, 2, 'Abigael is diligent and hardworking. Keep it Up dear.', 'Very good performance keep it up promoted to ss3', NOW(), NOW()),
(341, 8, 39, 100, 8, 'Favour is ready to learn and very attentive in class', 'Average performance. Try harder still.', NOW(), NOW()),
(433, 8, 39, 98, 10, 'Solomon is not serious with his studies, he needs to be monitored academically for better results.', 'Weak result you better sit up .\r\nPromoted to ss3 class', NOW(), NOW()),
(434, 8, 39, 96, 12, 'David is quit playful, he can perform better if he concentrates more in his studies.', 'Poor result promoted on trial to ss3 class', NOW(), NOW()),
(354, 8, 39, 98, 10, 'He is quiet and friendly', 'Good result. Keep it up.', NOW(), NOW()),
(435, 8, 39, 88, 20, 'Destiny is friendly and relates well with his peers, but he needs to be more focused in his studies ', 'Poor result promoted on trial to ss3 class', NOW(), NOW()),
(326, 8, 39, 106, 2, 'She learns faster and very attentive in class', 'Very good academic performance. Mercy is very industrious. Keep it up girl!', NOW(), NOW()),
(438, 8, 39, 92, 16, 'Opeyemi is a smart boy who needs to dedicate more time in his studies for better results.', 'Fair results promoted to ss3 c5', NOW(), NOW()),
(446, 8, 39, 98, 10, 'Khalid is humble and very friendly in class. He needs to concentrate more in his studies and avoid d', 'Good results promoted to ss3', NOW(), NOW()),
(327, 8, 39, 106, 2, 'She is calm and inquisitive', 'Fairly good result. Try harder!', NOW(), NOW()),
(408, 8, 39, 105, 3, 'Rachel is a well behaved student', 'Good results promoted to ss2', NOW(), NOW()),
(409, 8, 39, 106, 2, 'Uwem is too playful in class', 'Average performance promoted to ss2', NOW(), NOW()),
(410, 8, 39, 108, 0, 'Victory is too playful in class, although he is very serious with his studies', 'Good results promoted to ss2', NOW(), NOW()),
(330, 8, 39, 106, 2, 'She is intelligent and very active with her class activities', 'Excellent academic performance. Sofiyat is very hardworking. Please do not relent.', NOW(), NOW()),
(331, 8, 39, 108, 0, 'He gets carried away easily towards class activities', 'Not so good a result. Sit up', NOW(), NOW()),
(411, 8, 39, 106, 2, 'Joseph is a well behaved student', 'Average performance promoted to ss2', NOW(), NOW()),
(367, 8, 39, 104, 4, 'He is ready to learn and takes to correction quickly', 'Average academic performance. Try harder.', NOW(), NOW()),
(366, 8, 39, 102, 6, 'Gets distracted easily and plays a lots', 'Poor academic performance. Sit up!', NOW(), NOW()),
(365, 8, 39, 96, 12, 'She is attentive in class and grabs quickly', 'Average academic performance. Try harder still.', NOW(), NOW()),
(412, 8, 39, 104, 4, 'Enoch is a well behaved student', 'Excellent result keep it up promoted to ss2', NOW(), NOW()),
(413, 8, 39, 108, 0, 'Emmanuel is a well behaved student', 'Very good performance keep it up promoted to ss2', NOW(), NOW()),
(355, 8, 39, 104, 4, 'She is inquisitive and makes lots of friends', 'Tumba needs more activities and focus.', NOW(), NOW()),
(414, 8, 39, 87, 21, 'David is well behaved in the class', 'Average performance sit up promoted to ss2', NOW(), NOW()),
(415, 8, 39, 108, 0, 'Morenikeji is well behaved in the class', 'Good performance promoted to ss2', NOW(), NOW()),
(416, 8, 39, 106, 2, 'Victor is well behaved in the class', 'Very good performance promoted to ss2', NOW(), NOW()),
(417, 8, 39, 104, 4, 'Lekan is becoming a well behaved student', 'Poor result promoted on trial to ss2', NOW(), NOW()),
(418, 8, 39, 104, 4, 'Mercy is a very attentive in class', 'Poor result promoted on trial ss2', NOW(), NOW()),
(419, 8, 39, 108, 0, 'Esther a well behaved student', 'Good results promoted to ss2', NOW(), NOW()),
(356, 8, 39, 104, 4, 'She is friendly and attentive in class', 'Good result. Keep it up!', NOW(), NOW()),
(420, 8, 39, 100, 8, 'Anjola is very serious with her studies', 'Good performance promoted to ss2', NOW(), NOW()),
(358, 8, 39, 108, 0, 'He lacks concentration in class but ready to learn', 'Poor result. Sit up', NOW(), NOW()),
(422, 8, 39, 96, 12, 'Shola is too playful in the class', 'Poor result promoted on trial to ss2', NOW(), NOW()),
(357, 8, 39, 106, 2, 'She is active with her class work and also attentive', 'Average performance. Sit up.', NOW(), NOW()),;
