INSERT INTO Attendance (studentId, sessionId, termId, present, absent, teacherComment, principalComment, createdAt, updatedAt) VALUES
(17, 29, 43, 0, 0, 'Good performance. Royhan is very intentional about learning but needs to devote more time to studyin', 'Good performance but you can perform better. Promoted to SS2 class.', NOW(), NOW()),
(19, 29, 43, 118, 10, 'She is thoughtful in interactions with others.', 'Great performance! Keep it up !', NOW(), NOW()),
(134, 29, 43, 120, 8, 'She takes her classroom jobs seriously and demonstrates responsibility when completing them.', 'Average performance! With more concentration on your academics you can perform better.', NOW(), NOW()),
(135, 29, 43, 118, 10, 'He is always honest and can be counted on to recount information when asked.', 'Good performance! With more attention on your academics you can perform better.', NOW(), NOW()),
(100, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(102, 29, 43, 0, 0, 'Great Performance, keep soaring high Arnold!', 'Great performance! promoted to JSS2 class.', NOW(), NOW()),
(103, 29, 43, 0, 0, 'Average performance, sit up next time!', 'Average performance! You have to sit up!', NOW(), NOW()),
(104, 29, 43, 0, 0, 'Great Performance, keep soaring high Balogun!', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(105, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(106, 29, 43, 0, 0, 'A very exceptional and smart student. The sky is just your starting point!', 'Great performance! promoted to JSS2 class.', NOW(), NOW()),
(107, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(108, 29, 43, 0, 0, 'Average performance. He has the ability to do better if only he can put more effort on his academics', 'Fair performance! You have to sit up and focus on your academics.', NOW(), NOW()),
(109, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(110, 29, 43, 0, 0, 'Good performance but you have the capacity to do better', 'Fair performance! promoted to JSS2 class.', NOW(), NOW()),
(111, 29, 43, 0, 0, 'Average performance, sit up next time!', 'This is an average result, you need to sit up!', NOW(), NOW()),
(112, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(113, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Average performance! promoted to JSS2 class.', NOW(), NOW()),
(114, 29, 43, 0, 0, 'Average performance, sit up next time!', 'Average performance! you need to work harder next term', NOW(), NOW()),
(115, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(116, 29, 43, 0, 0, 'A good result but she has the capacity to do much better.', 'Fair performance! promoted to JSS2 class.', NOW(), NOW()),
(118, 29, 43, 0, 0, 'Average performance, sit up next time!', 'Fair performance! promoted to JSS2 class.', NOW(), NOW()),
(119, 29, 43, 0, 0, 'Great Performance, keep soaring high Angel!', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(120, 29, 43, 0, 0, 'Average performance, sit up next time!', 'Average performance! you need to sit up!', NOW(), NOW()),
(121, 29, 43, 0, 0, 'Olajide is an exceptional student. The sky is just her starting point!', 'Great performance! promoted to JSS2 class.', NOW(), NOW()),
(122, 29, 43, 0, 0, 'Average performance, sit up next time!', '', NOW(), NOW()),
(125, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(136, 29, 43, 0, 0, 'Good performance but there is room for improvement', 'Good performance! promoted to JSS2 class.', NOW(), NOW()),
(26, 30, 44, 116, 12, 'She can always be counted on to cooperate with her peers.', 'Good result Dolapo, the sky is just your starting point!', NOW(), NOW()),
(10, 30, 44, 122, 6, 'He cooperates consistently with the teacher and other students.', 'Outstanding performance. Keep it up.', NOW(), NOW()),
(13, 30, 44, 110, 18, 'He responds appropriately when corrected.', 'A good result. Keep up the effort.', NOW(), NOW()),
(15, 30, 44, 114, 14, 'She resists the urge to be distracted by other students.', 'A good result. Keep up the effort.', NOW(), NOW()),
(19, 30, 44, 118, 10, 'She is thoughtful in interactions with others.', 'A good result. Keep up the effort.', NOW(), NOW()),
(134, 30, 44, 120, 8, 'She takes her classroom jobs seriously and demonstrates responsibility when completing them.', 'A good result. Keep up the effort.', NOW(), NOW()),
(135, 30, 44, 118, 10, 'He is always honest and can be counted on to recount information when asked.', 'A good result. Keep up the effort.', NOW(), NOW()),
(142, 30, 44, 106, 22, 'She demonstrates her caring nature when helping her peers when they need the assistance.', 'A good result. Keep up the effort.', NOW(), NOW()),
(143, 30, 44, 110, 18, 'She does not give up when facing a task that is difficult and always does her best.', 'A fair performance. More effort is needed to improve.', NOW(), NOW()),
(22, 30, 44, 115, 13, 'He does not give up when facing a task that is difficult and always does his best.', 'Good result David, with more dedication on your academics you can perform better!', NOW(), NOW()),
(29, 30, 44, 120, 8, 'She is always enthusiastic when completing her work.', 'Good result Mfoniso, the sky is just your starting point!', NOW(), NOW()),
(1, 30, 44, 122, 6, 'Miracle is friendly and very active in class.', 'A good result. Keep up the effort.', NOW(), NOW()),
(99, 30, 44, 100, 28, '', '', NOW(), NOW()),
(101, 30, 44, 100, 28, '', '', NOW(), NOW()),
(112, 30, 44, 90, 38, '', '', NOW(), NOW()),
(124, 30, 44, 80, 48, '', '', NOW(), NOW()),
(140, 30, 44, 0, 128, '', '', NOW(), NOW()),
(141, 30, 44, 0, 128, '', '', NOW(), NOW()),
(153, 30, 44, 124, 4, 'You have the potential to do better. Put in more effort.', 'Good result, the sky is just your starting point!', NOW(), NOW()),
(154, 30, 44, 122, 6, 'You have done so well. Channel more strength to your weaknesses. Do not relent.', 'Impressive result, the sky is just your starting point!', NOW(), NOW()),
(155, 30, 44, 116, 12, 'You need to dedicate more time to study and practice. \nYou can do better, it all starts with you be', 'Poor result but you have the tendency to perform better next term!', NOW(), NOW()),
(156, 30, 44, 116, 12, 'You are always eager to learn. Do not feel discouraged.\nI believe in you and I need you to believe ', 'Average result but you have the tendency to perform better next term!', NOW(), NOW()),
(157, 30, 44, 123, 5, 'I see the enthusiasm to learn in you. Put in more effort and you will be proud of how great you will', 'Good result but you have the tendency to perform better!', NOW(), NOW()),
(159, 30, 44, 124, 4, 'Do not feel discouraged, you can do better. \nI need you to put in more effort.', 'Average result but you have the tendency to perform better!', NOW(), NOW()),
(161, 30, 44, 124, 4, 'I am proud of how excited you are about learning. \nChannel that excitement to your studies and you ', 'Good result but you have the tendency to perform better!', NOW(), NOW()),
(163, 30, 44, 128, 0, 'Well done! You can do better. This is not best you can do, the sky is your starting point.', 'Good result but you have the tendency to perform better!', NOW(), NOW()),
(164, 30, 44, 128, 0, 'You can really do better. I need you to limit the way you play and put more effort into your studies', 'Good result but you have the tendency to perform better!', NOW(), NOW()),
(165, 30, 44, 118, 10, 'I see the willingness to do better each day in you. Do not give up my dear.', 'Average result, but you have the tendency to perform better next term!', NOW(), NOW()),
(166, 30, 44, 128, 0, 'This is so impressive and I am really proud of how you have put in so much effort this term. \nThe g', 'Great result, the sky is just your starting point!', NOW(), NOW()),
(167, 30, 44, 114, 14, 'You can do better. This is just your starting point. Do not settle for less.', 'average result but you have the tendency to perform better next term!', NOW(), NOW()),
(168, 30, 44, 121, 7, 'Well done!\nYou are always ready to learn and I commend that. I want you to put in more effort.', 'Good result but you have the tendency to perform better next term!', NOW(), NOW()),
(172, 30, 44, 114, 14, 'You can do better. Please do not be non challant with your studies. \nThe best you desire is in you ', 'Poor result but you have the tendency to perform better next term!', NOW(), NOW()),
(114, 30, 44, 122, 6, 'He can do better, more seriousness in his studies', 'Poor result, you need to sit up Paul!', NOW(), NOW()),
(102, 30, 44, 126, 2, 'He is calm, inquisitive and ready to learn, more encouragement especially in his handwriting', 'Great result Arnold, keep it up!', NOW(), NOW()),
(122, 30, 44, 128, 0, 'She is easily distracted, more encouragement, she can do better', 'Average result, you can perform better with more dedication on your academics.', NOW(), NOW()),
(111, 30, 44, 124, 4, 'He is easily distracted, he can do better more seriousness, concentrations and encouragement', 'Poor result, you need to sit up!', NOW(), NOW()),
(3, 30, 44, 116, 12, 'Praise is gentle and respectful.', 'A good result. Keep up the effort.', NOW(), NOW()),
(17, 30, 44, 0, 128, '', '', NOW(), NOW()),
(32, 30, 44, 0, 128, '', '', NOW(), NOW()),
(34, 30, 44, 0, 128, '', '', NOW(), NOW()),
(36, 30, 44, 124, 4, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(38, 30, 44, 116, 12, 'A good performance. With continued effort, better results are possible.', 'Outstanding performance. Keep it up.', NOW(), NOW()),
(39, 30, 44, 0, 128, '', '', NOW(), NOW()),
(41, 30, 44, 98, 30, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(42, 30, 44, 0, 128, '', '', NOW(), NOW()),
(43, 30, 44, 110, 18, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(45, 30, 44, 0, 128, '', '', NOW(), NOW()),
(46, 30, 44, 124, 4, 'A good performance. With continued effort, better results are possible.', 'Outstanding performance. Keep it up.', NOW(), NOW()),
(52, 30, 44, 0, 128, '', '', NOW(), NOW()),
(54, 30, 44, 126, 2, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(55, 30, 44, 106, 22, 'A good performance. With continued effort, better results are possible.', 'A fair performance. More effort is needed to improve.', NOW(), NOW()),
(56, 30, 44, 124, 4, 'An excellent performance. Shows strong understanding and commitment.', 'Outstanding performance. Keep it up.', NOW(), NOW()),
(95, 30, 44, 124, 4, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(132, 30, 44, 126, 2, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(133, 30, 44, 106, 22, 'Performance is below expectation. Greater focus and hard work are required.', 'Below expectation. Serious improvement is required.', NOW(), NOW()),
(144, 30, 44, 118, 10, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(145, 30, 44, 124, 4, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(146, 30, 44, 116, 12, 'A good performance. With continued effort, better results are possible.', 'A good result. Keep up the effort.', NOW(), NOW()),
(147, 30, 44, 124, 4, 'A good performance. With continued effort, better results are possible.', 'A good performance. With continued effort, better results are possible.', NOW(), NOW()),
(87, 30, 44, 100, 28, '', '', NOW(), NOW()),
(92, 30, 44, 0, 128, '', '', NOW(), NOW()),
(100, 30, 44, 128, 0, 'He is ready to learn, more encouragement for better performances', 'Good result, the sky is just your starting point!', NOW(), NOW()),
(103, 30, 44, 0, 128, '', '', NOW(), NOW()),
(104, 30, 44, 126, 2, 'A good performance. With continued effort, better results are possible.', 'Good result, the sky is just the starting point!', NOW(), NOW()),
(105, 30, 44, 122, 6, 'A fair performance. More consistency and effort are needed.', 'Average result, you need to work harder.', NOW(), NOW()),
(106, 30, 44, 0, 128, '', '', NOW(), NOW()),
(107, 30, 44, 126, 2, 'A fair performance. More consistency and effort are needed.', 'Average result, you can perform better next term.', NOW(), NOW()),
(108, 30, 44, 128, 0, 'Performance is below expectation. Greater focus and hard work are required.', 'Poor result, with more dedication on your academics, you can perform better.', NOW(), NOW()),
(109, 30, 44, 0, 128, '', '', NOW(), NOW()),
(110, 30, 44, 0, 128, '', '', NOW(), NOW()),
(113, 30, 44, 128, 0, 'Performance is below expectation. Greater focus and hard work are required.', 'Average result, you need to work harder.', NOW(), NOW()),
(115, 30, 44, 128, 0, 'A good performance. With continued effort, better results are possible.', 'Good result but you have the tendency to perform better', NOW(), NOW()),
(116, 30, 44, 126, 2, 'A fair performance. More consistency and effort are needed.', 'Average result, you can perform better with more dedication on your academics.', NOW(), NOW()),;
