-- FULL USER/STUDENT MIGRATION (215 new users)
-- Run this file on the Railway database

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/95b9', 9, 'STUDENT', 'Ama-oyindamola', 'George', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/95b9', NULL, '', 'image.png', 'georgeamada2008@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/73e0', 9, 'STUDENT', 'Rachel', 'Uduimoh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/73e0', NULL, '', 'image.png', 'uduimoh@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/d86a', 9, 'STUDENT', 'Fatima', 'Yusuf', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/d86a', NULL, '', 'image.png', 'yusu@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/be9b', 9, 'STUDENT', 'Wisdom', 'Cletus', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/be9b', NULL, '', 'image.png', 'wisdomcletusjackson@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/24c0', 9, 'STUDENT', 'Aishat', 'Yusha\u, , , image.png, image.png, balkisuibrahim@gmail.com, 08077316160, Finished, NULL, , , , , , ', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/24c0', NULL, '', '', 'image.png');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/cf87', 9, 'STUDENT', 'Cliton', 'Omojola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/cf87', NULL, '', 'image.png', 'omojola@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/589f', 9, 'STUDENT', 'Tochuku', 'Thadeus', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/589f', NULL, '', 'image.png', 'thadeus@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/8117', 9, 'STUDENT', 'Micheal', 'Olajide', 'Olajide', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/8117', NULL, 'Olajide', 'image.png', 'tommymykel95@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/e822', 9, 'STUDENT', 'Mustapha', 'Abubakar', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/e822', NULL, '', 'image.png', 'abubakar@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/f1fc', 9, 'STUDENT', 'Kelvin', 'Okhai', 'Mr okhai', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/f1fc', NULL, 'Mrs okhai', 'image.png', 'makiokhai@gnail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/21a3', 9, 'STUDENT', 'Jessica', 'Uwadiale', 'Mr Uwadiale', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/21a3', NULL, 'Mrs Uwadiale', 'image.png', 'jessica@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/de48', 9, 'STUDENT', 'Shamsiyya', 'Usman', 'Usman Gali', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/de48', NULL, 'Safiya Usman', 'image.png', 'Aishatgali11@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/f5b2', 9, 'STUDENT', 'Olusoji Feranmi', 'David', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/f5b2', NULL, '', 'image.png', 'davidolusojiferanmi@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/760c', 9, 'STUDENT', 'Opeyemi', 'Ayeni', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/760c', NULL, '', 'image.png', 'opeyemioreoluwa04@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/5efa', 9, 'STUDENT', 'Sylvester', 'Adah', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/5efa', NULL, '', 'image.png', 'adahocheke236@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/ecfc', 9, 'STUDENT', 'Olayinka Sofiyah', 'Sanni', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/ecfc', NULL, '', 'image.png', 'sannisofiyah@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/a469', 9, 'STUDENT', 'Oyindamola Bolaji', 'Olowookere', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/a469', NULL, '', 'image.png', 'oyindamolabolaji8@gmai.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/fb63', 9, 'STUDENT', 'Martins Chibueze', 'Anyiam', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/fb63', NULL, '', 'image.png', 'chibueze@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/336c', 9, 'STUDENT', 'Favour', 'Imahia', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/336c', NULL, '', 'image.png', 'imarhiafranca@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/9922', 9, 'STUDENT', 'Hunaidatu', 'Muazu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/9922', NULL, '', 'image.png', 'muazu123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/6851', 9, 'STUDENT', 'Inioluwa', 'Awotunde', 'Mr Tosin Awotunde', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/6851', NULL, 'Mrs Hannah Awotunde', 'image.png', 'inioluwa@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/1dee', 9, 'STUDENT', 'Godwin', 'Ibe', 'Joeachim maduchem', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/1dee', NULL, 'Agustina maduchem', 'image.png', 'godwin12@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/48b2', 9, 'STUDENT', 'Lawrence', 'Patrick', 'Patrick', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/48b2', NULL, 'Patrick', 'image.png', 'Patrick123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/3865', 9, 'STUDENT', 'Marvellous', 'Akinola', 'Akinola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/3865', NULL, 'Akinola', 'image.png', 'akinyode13@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/512d', 9, 'STUDENT', 'Boluwatife Moropedaoluwa', 'Johnny', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/512d', NULL, '', 'image.png', 'moropedaoluwajohnny@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/1314', 9, 'STUDENT', 'Deborah Oghenemrore', 'Edijala', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/1314', NULL, '', 'image.png', 'edijaladeborah623@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/e447', 9, 'STUDENT', 'Micheal', 'Kayode', 'Mr Kayode', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/e447', NULL, 'Mrs Kayode', '1765017989_6934098598b4f.jpeg', 'kayode123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/3ed0', 9, 'STUDENT', 'Jushua', 'Okeke', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/3ed0', NULL, '', 'image.png', 'okekej123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/00eb', 9, 'STUDENT', 'Ademola', 'Adetayo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/00eb', NULL, '', 'image.png', 'ademola123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/f12f', 9, 'STUDENT', 'Jerry', 'Jwangwa', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/f12f', NULL, '', 'image.png', 'jerry@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/cbda', 9, 'STUDENT', 'Taiwo', 'Omoloja', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/cbda', NULL, '', 'image.png', 'taiwo123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/4366', 9, 'STUDENT', 'Opeyemi', 'Saheed', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/4366', NULL, '', 'image.png', 'opesaheed@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/04d3', 9, 'STUDENT', 'Pius', 'Iyobhebhe', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/04d3', NULL, '', 'image.png', 'pius123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/3e0c', 9, 'STUDENT', 'Ifeanyi Emmanuel', 'Emebene', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/3e0c', NULL, '', 'image.png', 'Emmanuel@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/c7e2', 9, 'STUDENT', 'Daniel', 'Uti', 'Uti', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/c7e2', NULL, 'Uti', 'image.png', 'daniel123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/42dd', 9, 'STUDENT', 'Faranpojo', 'David', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/42dd', NULL, '', 'image.png', 'Davies@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/0afb', 9, 'STUDENT', 'Divine', 'Bekeh', 'Mr Bekeh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/0afb', NULL, 'Mrs Bekeh', 'image.png', 'divineiper34@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/f726', 9, 'STUDENT', 'Serah', 'Salihu', 'Mr salihu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/f726', NULL, 'Mrs salihu', 'image.png', 'serah123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/8c69', 9, 'STUDENT', 'Favour', 'Mbikpo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/8c69', NULL, '', 'image.png', 'favour@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2022/78ce', 9, 'STUDENT', 'Test', 'Test', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2022/78ce', NULL, '', 'image.png', 'tinggtechnologies@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/4426', 9, 'STUDENT', 'Amirat', 'Abdulwahab', 'Mr Abdulwahab', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/4426', NULL, 'Mrs Abdulwahab', 'image.png', 'amirat124@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/ddcc', 9, 'STUDENT', 'Albert', 'Obaro', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/ddcc', NULL, '', 'image.png', 'obaro@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/b000', 9, 'STUDENT', 'Sofiat', 'Shuttu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/b000', NULL, '', 'image.png', 'shuttusofiat@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/5f7a', 9, 'STUDENT', 'Lilian', 'Amasetimin', 'Mr Amasitimin', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/5f7a', NULL, 'Mrs Amasetimin', 'image.png', 'lilian@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/9379', 9, 'STUDENT', 'Malmoud', 'Adamu', 'Mr Adamu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/9379', NULL, 'Mrs Adamu', 'image.png', 'adamu123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/833e', 9, 'STUDENT', 'Favour', 'Okolie', 'Mr Okolie', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/833e', NULL, 'Mrs Okolie', 'image.png', 'okolie@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/735f', 9, 'STUDENT', 'Fredrick', 'Etop', 'Etop', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/735f', NULL, 'Victory', 'image.png', 'Frederic23@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/ac78', 9, 'STUDENT', 'Haliat', 'Idowu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/ac78', NULL, '', 'image.png', 'idowi123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/86bc', 9, 'STUDENT', 'Sheidu', 'Emmanuel', 'Sheidu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/86bc', NULL, 'Sheidu', 'image.png', 'emannue@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/50bf', 9, 'STUDENT', 'Rukayat', 'Adamu', 'Adamu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/50bf', NULL, 'Adamu', 'image.png', 'rukayat@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/ed04', 9, 'STUDENT', 'Joseph', 'Ndunche', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/ed04', NULL, '', 'image.png', 'tinggtechnologies@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/0eb7', 9, 'STUDENT', 'Obera Emmanuel', 'Emmanuel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/0eb7', NULL, '', 'image.png', 'Emmanuel@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/02ef', 9, 'STUDENT', 'Blessing', 'Samuel', 'Samuel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/02ef', NULL, 'Samuel', 'image.png', 'samuel123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/5a35', 9, 'STUDENT', 'Precious', 'Osas', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/5a35', NULL, '', 'image.png', 'oselueku@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/2586', 9, 'STUDENT', 'Ajibola Sultol', 'Ibrahim', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/2586', NULL, '', 'image.png', 'ibrahim@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/ef63', 9, 'STUDENT', 'Favour', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/ef63', NULL, '', 'image.png', 'philip123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/f1a0', 9, 'STUDENT', 'Boluwatife', 'Oladimeji', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/f1a0', NULL, '', 'image.png', 'boluwatife@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/7d96', 9, 'STUDENT', 'Adeworan', 'Adeola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/7d96', NULL, '', 'image.png', 'adeola123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/7ab5', 9, 'STUDENT', 'Ruth Oyindamola', 'Ogunjobi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/7ab5', NULL, '', 'image.png', 'ruth123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/81ca', 9, 'STUDENT', 'Ruth Oyindamola', 'Ogunjobi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/81ca', NULL, '', 'image.png', 'ruth123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/6201', 9, 'STUDENT', 'Dominica', 'Anyanwa', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/6201', NULL, '', 'image.png', 'dominica@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/d325', 9, 'STUDENT', 'Elizabeth', 'Ezekiel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/d325', NULL, '', 'image.png', 'ezekiel123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/a2d9', 9, 'STUDENT', 'Elizabeth', 'Ezekiel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/a2d9', NULL, '', 'image.png', 'ezekiel123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/ecdb', 9, 'STUDENT', 'Adiza', 'Bello', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/ecdb', NULL, '', 'image.png', 'adiza123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/38c6', 9, 'STUDENT', 'Abdulahi', 'Suliman', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/38c6', NULL, '', 'image.png', 'sulima123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/119a', 9, 'STUDENT', 'Muhammed  Awan', 'Hussein', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/119a', NULL, '', 'image.png', 'hussein123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/fad5', 9, 'STUDENT', 'Grace', 'Iziokhi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/fad5', NULL, '', 'image.png', 'grace123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/fe62', 9, 'STUDENT', 'David', 'Richmond', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/fe62', NULL, '', 'image.png', 'david123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/dd3f', 9, 'STUDENT', 'Destiny', 'Ipere', 'Paul ipere', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/dd3f', NULL, 'Rita ipere', 'image.png', 'paulipere367@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/b08c', 9, 'STUDENT', 'Bright', 'Daniela', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/b08c', NULL, '', 'image.png', 'bright123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/78ad', 9, 'STUDENT', 'Praise', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/78ad', NULL, '', 'image.png', 'praise123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/f17f', 9, 'STUDENT', 'Ochechi', 'Rose', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/f17f', NULL, '', 'image.png', 'rose123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/cfdd', 9, 'STUDENT', 'Precious', 'Omeje', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/cfdd', NULL, '', 'image.png', 'precious123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/1037', 9, 'STUDENT', 'Fiyinfoluwa', 'Sahley', 'Mr Sahley', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/1037', NULL, 'Mrs Sahley', 'image.png', 'fiyin123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/c974', 9, 'STUDENT', 'Favour', 'Mobolaji', 'Mr Mobolaji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/c974', NULL, 'Mrs Mobolaji', 'image.png', 'favour123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/4e74', 9, 'STUDENT', 'Mfoniso', 'Otobong', 'Mr Asukwo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/4e74', NULL, 'Mrs Asukwo', 'image.png', 'otobong124@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/3e7c', 9, 'STUDENT', 'Joshua  Ayomide', 'Ogunjobi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/3e7c', NULL, '', 'image.png', 'joshua123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/b343', 9, 'STUDENT', 'Ruth', 'Ogunjobi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/b343', NULL, '', 'image.png', 'ogunjobi123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/a551', 9, 'STUDENT', 'Destiny', 'Ipere', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/a551', NULL, '', 'image.png', 'destiny123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/ff90', 9, 'STUDENT', 'Richmond', 'David', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/ff90', NULL, '', 'image.png', 'richmond@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/52a1', 9, 'STUDENT', 'Murayo', 'Micheal', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/52a1', NULL, '', 'image.png', 'mcbeal123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/d808', 9, 'STUDENT', 'Precious', 'Omeje', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/d808', NULL, '', 'image.png', 'precious223@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/4b53', 9, 'STUDENT', 'Adeola', 'Adeworan', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/4b53', NULL, '', 'image.png', 'adeola123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/880b', 9, 'STUDENT', 'Muhammed', 'Hussein', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/880b', NULL, '', 'image.png', 'muhammed123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/3883', 9, 'STUDENT', 'Ajibola', 'Ibrahim', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/3883', NULL, '', 'image.png', 'ibrahim2@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/c303', 9, 'STUDENT', 'Praise', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/c303', NULL, '', 'image.png', 'praise123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/a46f', 9, 'STUDENT', 'Daniella', 'Bright', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/a46f', NULL, '', 'image.png', 'daniel123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/4ecc', 9, 'STUDENT', 'Hadizah', 'Bello', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/4ecc', NULL, '', 'image.png', 'bello123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/d59a', 9, 'STUDENT', 'Elizabeth', 'Ezekiel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/d59a', NULL, '', 'image.png', 'elizabeth123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/7b79', 9, 'STUDENT', 'Favour', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/7b79', NULL, '', 'image.png', 'favour123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/fb57', 9, 'STUDENT', 'Suliman', 'Abdullahi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/fb57', NULL, '', 'image.png', 'sulima123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/a54e', 9, 'STUDENT', 'Grace', 'Iziokhai', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/a54e', NULL, '', 'image.png', 'grace13@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/936e', 9, 'STUDENT', 'Roseline', 'Ochechi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/936e', NULL, '', 'image.png', 'ochechi@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/8f9d', 9, 'STUDENT', 'Boluwatife', 'Oladimeji', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/8f9d', NULL, '', 'image.png', 'boluwatife@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/6ca2', 9, 'STUDENT', 'Daniella', 'Anyanwu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/6ca2', NULL, '', 'image.png', 'daniella11@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/8bb8', 9, 'STUDENT', 'Mercy', 'Olabiyi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/8bb8', NULL, '', 'image.png', 'mercy123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/1f48', 9, 'STUDENT', 'Omotola', 'Balogun', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/1f48', NULL, '', 'image.png', 'balkisuibrahim@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/db41', 9, 'STUDENT', 'Usman', 'Yusuf', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/db41', NULL, '', 'image.png', 'yusuf1232@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/cc05', 9, 'STUDENT', 'Aliyah', 'Bello', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/cc05', NULL, '', 'image.png', 'bello123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/c453', 9, 'STUDENT', 'Oyindamola', 'Akinsola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/c453', NULL, '', 'image.png', 'akinyode12@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/7014', 9, 'STUDENT', 'Aishat', 'Abdulrasak', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/7014', NULL, '', 'image.png', 'aishat123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/d777', 9, 'STUDENT', 'Gift', 'Chukwu', 'Mr Chukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/d777', NULL, 'Mrs chukwu', 'image.png', 'gift123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/3607', 9, 'STUDENT', 'Emmanuel', 'Obera', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/3607', NULL, '', 'image.png', 'obaro@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/dec8', 9, 'STUDENT', 'Anabell chikezie', 'Kelechi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/dec8', NULL, '', 'image.png', 'kelechi@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/adc9', 9, 'STUDENT', 'Precious', 'Osas', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/adc9', NULL, '', 'image.png', 'osas123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/6721', 9, 'STUDENT', 'James', 'Ugbeh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/6721', NULL, '', 'image.png', 'james321@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2023/198e', 9, 'STUDENT', 'John', 'Ugebeh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2023/198e', NULL, '', 'image.png', 'john12@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/abde', 9, 'STUDENT', 'Goodness  Odion', 'Odion', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/abde', NULL, '', 'image.png', 'oselueku@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/f33e', 9, 'STUDENT', 'Mercy Akhere', 'Odion', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/f33e', NULL, '', 'image.png', 'oselueku@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/509d', 9, 'STUDENT', 'Olabosipo', 'Akinleye', 'Mr Akinleye', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/509d', NULL, 'Mrs Akinleye', 'image.png', 'akinleye@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/e2f1', 9, 'STUDENT', 'Goodness', 'Emmanuel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/e2f1', NULL, '', 'image.png', 'emmauel87@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/4085', 9, 'STUDENT', 'Blessing', 'Nkwocha', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/4085', NULL, '', 'image.png', 'ngocha12@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/b34e', 9, 'STUDENT', 'Monsurat Opeoluwa', 'Oyedepo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/b34e', NULL, '', 'image.png', 'oyedepo123@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/b4cd', 9, 'STUDENT', 'Christabel', 'Iyoha', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/b4cd', NULL, '', 'image.png', 'Christabe21@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('student/2024/34d4', 9, 'STUDENT', 'Melissa', 'Ogherena', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'student/2024/34d4', NULL, '', 'image.png', 'melissa@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/cc2e', 9, 'STUDENT', 'Akinnifesi', 'Clara', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/cc2e', NULL, '', 'image.png', 'odionandy@yahoo.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/e52e', 9, 'STUDENT', 'Gift', 'Chukwu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/e52e', NULL, '', 'image.png', 'chukwu32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/e560', 9, 'STUDENT', 'Quadri', 'Adeyanju', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/e560', NULL, '', 'image.png', 'adeyanju@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/16ac', 9, 'STUDENT', 'Ayodele', 'Goodness', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/16ac', NULL, '', 'image.png', 'ayodelejs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/2a63', 9, 'STUDENT', 'Elizabeth', 'Iwelunmo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/2a63', NULL, '', 'image.png', 'eIwelunmojs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/e227', 9, 'STUDENT', 'David', 'Akinola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/e227', NULL, '', 'image.png', 'davidjs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/9cc5', 9, 'STUDENT', 'Victory', 'Iriah', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/9cc5', NULL, '', 'image.png', 'victoryjs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/492d', 9, 'STUDENT', 'Gideon', 'Bisiriyu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/492d', NULL, '', 'image.png', 'gideonjs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/2b9a', 9, 'STUDENT', 'Nifemi', 'Olajide', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/2b9a', NULL, '', 'image.png', 'nifemijs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/0644', 9, 'STUDENT', 'Success', 'Oghene', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/0644', NULL, '', 'image.png', 'successjs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/6c9b', 9, 'STUDENT', 'Divine', 'Labija', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/6c9b', NULL, '', 'image.png', 'divinejs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/912d', 9, 'STUDENT', 'Destiny', 'Mbkpo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/912d', NULL, '', 'image.png', 'destinyjs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/0e74', 9, 'STUDENT', 'Obehi Gift', 'Ogunleye', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/0e74', NULL, '', 'image.png', 'obehijs1@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/e4cc', 9, 'STUDENT', 'Imran', 'Bilal', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/e4cc', NULL, '', 'image.png', 'imran33@gail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/a285', 9, 'STUDENT', 'Divine Faour', 'Adewale', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/a285', NULL, '', 'image.png', 'divine43@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/16fd', 9, 'STUDENT', 'Emmanuella', 'Oluya', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/16fd', NULL, '', 'image.png', 'oluya32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/850f', 9, 'STUDENT', 'Owen', 'Richard Ebenezer', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/850f', NULL, '', 'image.png', 'owen43@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/5ed2', 9, 'STUDENT', 'Godspower', 'Oluwole', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/5ed2', NULL, '', 'image.png', 'oluwole43@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/7cc1', 9, 'STUDENT', 'Gold', 'Akinyode', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/7cc1', NULL, '', 'image.png', 'gold321@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/6889', 9, 'STUDENT', 'Nifemi', 'Adebowale', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/6889', NULL, '', 'image.png', 'nifemi32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/cf4a', 9, 'STUDENT', 'Yasirah', 'Lawal Isa', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/cf4a', NULL, '', 'image.png', 'yasirah43@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/f6e4', 9, 'STUDENT', 'Precious', 'Isaac', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/f6e4', NULL, '', 'image.png', 'precious12@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/b6a8', 9, 'STUDENT', 'Ben', 'Clinton', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/b6a8', NULL, '', 'image.png', 'ben76@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/f99c', 9, 'STUDENT', 'Ben', 'Victor', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/f99c', NULL, '', 'image.png', 'victor32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/721d', 9, 'STUDENT', 'Olohimai Michelle', 'Philip', 'Philip Eguaomon Uanserume', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/721d', NULL, 'Faith Azumi Philip Uanserume', 'image.png', 'philipuans4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/f0f3', 9, 'STUDENT', 'Amidat', 'Fadare', 'Mr Fadare', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/f0f3', NULL, 'Mrs Fadare', 'image.png', 'fadare32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/e854', 9, 'STUDENT', 'Elizabeth', 'Oluya', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/e854', NULL, '', 'image.png', 'oluya32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/ee4e', 9, 'STUDENT', 'Emmanuel', 'Patrick', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/ee4e', NULL, '', 'image.png', 'Patric43@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/ef24', 9, 'STUDENT', 'Prospect', 'Chiabuotu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/ef24', NULL, '', 'image.png', 'prospect32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/ba60', 9, 'STUDENT', 'Caleb', 'Adekonya', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/ba60', NULL, '', 'image.png', 'caleb32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/0f81', 9, 'STUDENT', 'Chikamso Stanley', 'Umunna', 'Umunna Innocent Chukwuemeka', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/0f81', NULL, 'Umunna Chioma Chinasa', 'image.png', 'obelechy@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/64c1', 9, 'STUDENT', 'Alex', 'Anthony', 'Anthony Musa', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/64c1', NULL, 'Christiana Anthony', 'image.png', 'alex21@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/b311', 9, 'STUDENT', 'Khalid', 'Ismail', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/b311', NULL, '', 'image.png', 'khalid32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/b29a', 9, 'STUDENT', 'Lifted', 'James Praise', 'Mr James Praise', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/b29a', NULL, 'Mrs James Praise', 'image.png', 'jamespraiselifted@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/960d', 9, 'STUDENT', 'Taiwo marvellous', 'Ajaye', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/960d', NULL, '', 'image.png', 'ajaye12@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/5189', 9, 'STUDENT', 'Kehinde mercy', 'Ajayi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/5189', NULL, '', 'image.png', 'ajayi32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/ae18', 9, 'STUDENT', 'Enoch Ohizimede', 'Oluya', 'OLUYA GREGORY OGBETA', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/ae18', NULL, 'OLUYA AGNES OLUBUNMI', 'image.png', 'oluya23@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/1ed8', 9, 'STUDENT', 'Peace Chiwendu', 'Eze', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/1ed8', NULL, '', 'image.png', 'eze32@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/ac01', 9, 'STUDENT', 'Oseremhen', 'Iyere', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/ac01', NULL, '', 'image.png', 'iyere21@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/425c', 9, 'STUDENT', 'Precious', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/425c', NULL, '', 'image.png', 'previou23@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/9b71', 9, 'STUDENT', 'Sultan Timilehin', 'Ismail', 'Ismail Ibrahim', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/9b71', NULL, 'Ismail omowunmi', 'image.png', 'ismailtimilehin257@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/cbc9', 9, 'STUDENT', 'Ize Fridaus', 'Muhammad', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/cbc9', NULL, '', 'image.png', 'ize@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/5cd4', 9, 'STUDENT', 'Victor Oluwaseun', 'Akinnifesi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/5cd4', NULL, '', 'image.png', 'victor@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/6395', 9, 'STUDENT', 'Testimony', 'Iriah', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/6395', NULL, '', 'image.png', 'iriatre23@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/cd24', 9, 'STUDENT', 'Aliyat', 'Idowu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/cd24', NULL, '', 'image.png', 'aliyat55@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/229c', 9, 'STUDENT', 'Patrick', 'Emmanuel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/229c', NULL, '', 'image.png', 'emmanueloo34@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/14ef', 9, 'STUDENT', 'Samuel', 'Omeje', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/14ef', NULL, '', 'image.png', 'omejezx@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2024/2d9a', 9, 'STUDENT', 'Sultan', 'Ismail', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2024/2d9a', NULL, '', 'image.png', 'ismailoi@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/0669', 9, 'STUDENT', 'Ibukun', 'Akinyemi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/0669', NULL, '', 'image.png', 'Ibuku54@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/9d71', 9, 'STUDENT', 'ONUH', 'PRECIOUS', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/9d71', NULL, '', 'image.png', 'preciousnes@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/b8f5', 9, 'STUDENT', 'Immaculate', 'Nwabudike', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/b8f5', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/f2e9', 9, 'STUDENT', 'Awwal', 'Lawal', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/f2e9', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/822e', 9, 'STUDENT', 'Fareedah', 'Jimoh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/822e', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/dc58', 9, 'STUDENT', 'Victory', 'Adewale', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/dc58', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/4148', 9, 'STUDENT', 'Monica', 'Agwo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/4148', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/9b1a', 9, 'STUDENT', 'Elijah', 'Benjamin', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/9b1a', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/ce09', 9, 'STUDENT', 'Goodluck', 'Ikor', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/ce09', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/a339', 9, 'STUDENT', 'vanessa', 'Isong', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/a339', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/277f', 9, 'STUDENT', 'Ayoritse', 'Atafiri', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/277f', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/f166', 9, 'STUDENT', 'Success', 'Olom', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/f166', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/0a9f', 9, 'STUDENT', 'ISAAC', 'DIVINE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/0a9f', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/5187', 9, 'STUDENT', 'Godwin', 'Oluwole', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/5187', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/949f', 9, 'STUDENT', 'ISAAC', 'ANTHONY', 'Anthony Musa', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/949f', NULL, 'Christiana Anthony', 'image.png', 'IsaacAnthony4@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/d612', 9, 'STUDENT', 'DAVID', 'OTEGBAYO', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/d612', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/e0c9', 9, 'STUDENT', 'JOEL', 'CHRISTIAN', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/e0c9', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/0310', 9, 'STUDENT', 'VICTORY', 'AKAOGWU', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/0310', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/6396', 9, 'STUDENT', 'SEKEMI', 'ORISAWUYI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/6396', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/3eb6', 9, 'STUDENT', 'IFEOLUWA', 'AKINYEMI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/3eb6', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/16fe', 9, 'STUDENT', 'ANNABEL', 'IYOHA', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/16fe', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/7d20', 9, 'STUDENT', 'JOY', 'DURU', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/7d20', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/cfc2', 9, 'STUDENT', 'ANIBIJUWON', 'ELIZABETH', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/cfc2', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/25d3', 9, 'STUDENT', 'DOMINION', 'ENAKAHIRE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/25d3', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/e081', 9, 'STUDENT', 'FARUQ', 'ADIGUN FADERE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/e081', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/ace9', 9, 'STUDENT', 'MASARAT', 'IBUOWO', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/ace9', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/bab7', 9, 'STUDENT', 'KING DAVID', 'AKINJO', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/bab7', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/beb0', 9, 'STUDENT', 'HALEEMAT', 'AMEED', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/beb0', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/c58a', 9, 'STUDENT', 'ZAMAT', 'LAWAL', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/c58a', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/7702', 9, 'STUDENT', 'KAMSI', 'NZEWI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/7702', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/ebe4', 9, 'STUDENT', 'FAVOUR', 'NWABUDIKE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/ebe4', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/6d99', 9, 'STUDENT', 'JESSICA', 'UGBEH', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/6d99', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/0538', 9, 'STUDENT', 'Mariam', 'Adamu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/0538', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/5382', 9, 'STUDENT', 'PEACE', 'INNOCENT', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/5382', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/1c37', 9, 'STUDENT', 'AMIDAT', 'ADIGUN FADERE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/1c37', NULL, '', 'image.png', 'adigunfadareaminat@gmai.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/022f', 9, 'STUDENT', 'Unknown', '', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/022f', NULL, '', 'image.png', 'image.png');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/c5b8', 9, 'STUDENT', 'Unknown', '', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/c5b8', NULL, '', 'image.png', 'image.png');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/d23d', 9, 'STUDENT', 'Unknown', '', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/d23d', NULL, '', 'image.png', 'admin2');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/cbdb', 9, 'STUDENT', 'DISU', 'AL\AMEEN, , , image.png, , auspom4real@gmail.com, 08062093770, SS2A, Male, , , , , , $2y$10$bP01QU7L', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/cbdb', NULL, '', '', 'image.png');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/6732', 9, 'STUDENT', 'SULAINMAN', 'BARAKAT', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/6732', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/e63b', 9, 'STUDENT', 'CRISTIANO', 'IDEMUDIA', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/e63b', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/9ec1', 9, 'STUDENT', 'CRISTIANO', 'IDEMUDIA', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/9ec1', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/8ec8', 9, 'STUDENT', 'OLUWAFERANMI', 'OLAJIDE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/8ec8', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/1c47', 9, 'STUDENT', 'ONUH', 'PRECIOUS', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/1c47', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/6752', 9, 'STUDENT', 'SAMUEL', 'OMENJE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/6752', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/ff09', 9, 'STUDENT', 'IBUKUNOLUWA', 'AKINYEMI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/ff09', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/ed86', 9, 'STUDENT', 'PROMISE', 'TAIWO', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/ed86', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2025/1522', 9, 'STUDENT', 'OLOHIMAI MICHELLE', 'PHILIP', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2025/1522', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2026/e6a9', 9, 'STUDENT', 'Suliamon', 'Qosim', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2026/e6a9', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2026/1cd7', 9, 'STUDENT', 'GRACE', 'AFOLABI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2026/1cd7', NULL, '', 'image.png', 'auspom4real@gmail.com');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2026/73eb', 8, 'STUDENT', 'Qozeem Babatunde', '', 'Atoba', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2026/73eb', 13, '', '', 'image.png');

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES ('greatkings/2026/2913', 8, 'STUDENT', 'Tolulope', '', 'Olalere', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'); SET @uid = LAST_INSERT_ID(); INSERT INTO Student (userId, studentNo, classRoomId, fatherName, motherName, parentImage) VALUES (@uid, 'greatkings/2026/2913', 12, '', '', 'image.png');