-- Missing Users Migration (521 users)
-- Run these queries in order:

INSERT INTO User (uniqueId, schoolId, role, firstName, middleName, lastName, password, status) VALUES
('greatkings/2022/f058', 9, 'STUDENT', 'Mercy   Fumilayo', 'shadrach', 'Mercy', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/b936', 9, 'STUDENT', 'Davina-Blessing Onyinyechukwu', 'Onwurah', 'Stanley uchenna onwurah', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/728d', 9, 'STUDENT', 'Yesiraa', 'Muazu', 'Yesira', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/8d5f', 9, 'STUDENT', 'Semilore  Esther', 'Bisiriyu', 'Bisiriyu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/4727', 9, 'STUDENT', 'Sofiyat Abike', 'Kewulere', 'Sofiat', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/ccd7', 9, 'STUDENT', 'Goodluck', 'Ishaya', 'Goodluck', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/4eb1', 9, 'STUDENT', 'Zainab Temitope', 'Abdulrahmon', 'Abdulraman', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1e56', 9, 'STUDENT', 'Esther Fiyinfoluwa', 'Orisawuyi', 'Orisawuyi Abolaji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/9e48', 9, 'STUDENT', 'Esther', 'Akindojutimi', 'Akin', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/30a3', 9, 'STUDENT', 'Aliyat', 'Adetokun', 'Adetokun', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/a796', 9, 'STUDENT', 'Yaminah', 'Muazu', 'Muazu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/82ea', 9, 'STUDENT', 'Sadiya', 'Abdullahi', 'Abdulahi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/960f', 9, 'STUDENT', 'Ogheneochuko', 'Enakarhire', 'Enakhahire', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/ba73', 9, 'STUDENT', 'Mercy Eniola', 'George', 'Mercy', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/be4a', 9, 'STUDENT', 'Haleeyah Omoshalewa', 'Alakoso', 'Haleeyah', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/06cc', 9, 'STUDENT', 'Favour Nnesoma', 'Ifeanyichukwu', 'Mr ifeanyi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/2caa', 9, 'STUDENT', 'Favour Chinaza', 'Mbikpo', 'Mr Mbikpo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/a592', 9, 'STUDENT', 'Victory', 'Imahia', 'Imarhia', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/5d81', 9, 'STUDENT', 'Mubarak', 'Ibuowo', 'Ibuowo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/68b3', 9, 'STUDENT', 'Titilayo Deborah', 'Adebayo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/36dc', 9, 'STUDENT', 'Victory', 'Ezekiel', 'Ezekiel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1ff4', 9, 'STUDENT', 'Miracle', 'Odion', 'Odion', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/4f4e', 9, 'STUDENT', 'Mubarak', 'Jimoh', 'Jimoh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/5e7c', 9, 'STUDENT', 'Oluwaferanmi', 'Olajide', 'Olajide', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1467', 9, 'STUDENT', 'Meshach', 'Okafor', 'Okafor', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3ff5', 9, 'STUDENT', 'Richard', 'Azuh', 'Azuh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/e3f9', 9, 'STUDENT', 'Queen', 'Akinyode', 'Akinyode', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/0e6f', 9, 'STUDENT', 'Waris', 'Alabi', 'Mr Alabi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/4d97', 9, 'STUDENT', 'Richard Oluwatodimu', 'Olajide', 'Mr Olajide', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/dfe8', 9, 'STUDENT', 'Esther', 'Tumba', 'Tumba Ibrahim', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/4478', 9, 'STUDENT', 'Haliyat', 'Bolarinwa-oshokoya', 'Mr Bolarinwa', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/7266', 9, 'STUDENT', 'Destiny', 'Akogwu', 'AKOGWU PETER', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/783e', 9, 'STUDENT', 'Caleb', 'Effiong', 'Mr effiong', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/9781', 9, 'STUDENT', 'Fumilayo', 'Adeshina', 'Mr Adeshina', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/be89', 9, 'STUDENT', 'Ayodeji', 'Fatunmbi', 'Mr fatunmbi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/f4d8', 9, 'STUDENT', 'David', 'Ilori', 'Mr ilori', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/2bd8', 9, 'STUDENT', 'Shilony', 'Onyekwena', 'Mr Onyekwena', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/4c52', 9, 'STUDENT', 'Joy', 'Iriah', 'Mr Iriah', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/d40b', 9, 'STUDENT', 'Iremide', 'Lande', 'Mr Lande', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/20f9', 9, 'STUDENT', 'Halimat', 'Yaya', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/702a', 9, 'STUDENT', 'Ramadan', 'Lawal', 'Mr lawal', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1098', 9, 'STUDENT', 'Good luck', 'Hamzat', 'Mr Hamzat', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/6784', 9, 'STUDENT', 'Oluwapelumi', 'Olufemi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/fee0', 9, 'STUDENT', 'Oreoluwa', 'Olatunji', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/ac5a', 9, 'STUDENT', 'Julianah', 'Asuquo', 'Mr Asuquo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/68d5', 9, 'STUDENT', 'Emem', 'Usoroh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/0230', 9, 'STUDENT', 'Emmanuella', 'India', 'Mr India', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/181c', 9, 'STUDENT', 'Husseinat', 'Abubakar', 'Mr Abubakar', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/0cbc', 9, 'STUDENT', 'Ezekiel', 'Oluwasegun', 'Mr Oluwasegun', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/775c', 9, 'STUDENT', 'Timilehin', 'Oyewusi', 'Mr Rotimi Oyewusi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/806e', 9, 'STUDENT', 'Oyinkansola', 'Akinrinola', 'Mr Akinrinola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1efb', 9, 'STUDENT', 'Ehosa', 'Nosa', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/9dd7', 9, 'STUDENT', 'Adeola', 'Adeniyi', 'Mr Adenyi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/7c2c', 9, 'STUDENT', 'Oluwanifemi', 'Olubode', 'Mr Olubode', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3f3e', 9, 'STUDENT', 'Grace', 'Ameh', 'Mr Ameh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/ec53', 9, 'STUDENT', 'Faith', 'Oghene', 'Mr Oghene', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/70a2', 9, 'STUDENT', 'Hassan', 'Abubakar', 'Mr Abubakar', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/97ba', 9, 'STUDENT', 'Daniella', 'Ademoluta', 'Mr Ademoluti', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/df4c', 9, 'STUDENT', 'Saratu', 'Aliyu', 'Mr Aliu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/42e7', 9, 'STUDENT', 'Israel', 'John', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/7983', 9, 'STUDENT', 'Uche', 'Duru', 'Mr Duru', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/5ef8', 9, 'STUDENT', 'Favour', 'Akinriola', 'Mr Akinriola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/ef59', 9, 'STUDENT', 'Esther', 'Adesokan', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/ad17', 9, 'STUDENT', 'Abideen', 'Aderoju', 'Mr Aderoju', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/acd6', 9, 'STUDENT', 'Kehinde', 'Omojola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/64e1', 9, 'STUDENT', 'Yusuf', 'Amusan', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/0327', 9, 'STUDENT', 'John', 'Adeniyi', 'Mr Adenyi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/d0b4', 9, 'STUDENT', 'Ewajesu', 'Shadrach', 'Mr Shadrack', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/9095', 9, 'STUDENT', 'Irenitemi', 'Olayori', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/d569', 9, 'STUDENT', 'Victor', 'Onwe', 'Mr Onwe', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/b864', 9, 'STUDENT', 'Divine', 'Ipere', 'Ipere', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/0a7d', 9, 'STUDENT', 'Eshikhena', 'Obiita Habibat', 'Eshikhena AbdulRahman  Oghele', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/699f', 9, 'STUDENT', 'Victor', 'Habila', 'Habila', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/70d1', 9, 'STUDENT', 'David', 'Ogbonna', 'Ogbenna', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/7a1e', 9, 'STUDENT', 'Roland', 'Nwaigwue', 'Nwaigwe', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/73d4', 9, 'STUDENT', 'Blessing', 'Duru', 'Mr Duru', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/d66b', 9, 'STUDENT', 'Victoria', 'Habila', 'Habila', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3f85', 9, 'STUDENT', 'Hunaidatu', 'Muazu', 'Muazu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/2d5d', 9, 'STUDENT', 'James', 'Bobani', 'Mr Bobani', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/72ee', 9, 'STUDENT', 'Havilah', 'Labija', 'Labijah', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1bfa', 9, 'STUDENT', 'Testimony', 'Ndunche', 'Mr Ndunche', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/2ecf', 9, 'STUDENT', 'Ademola', 'Adeworan', 'Adeworan', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/d41b', 9, 'STUDENT', 'Rachel', 'Onwurah', 'Mr onwurah', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/70be', 9, 'STUDENT', 'Uwem', 'Usoroh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/28e1', 9, 'STUDENT', 'Victory', 'Isaac', 'Mr Isaac', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/70a0', 9, 'STUDENT', 'Joseph', 'Abolade', 'Abolade', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/5f82', 9, 'STUDENT', 'Enoch', 'Agboola', 'Agboola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/95ef', 9, 'STUDENT', 'Emmanuel', 'Abebe', 'Abebe', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3037', 9, 'STUDENT', 'David', 'Nwanze', 'Nwanze', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/bfa1', 9, 'STUDENT', 'Morenikeji', 'Alonge', 'Mr Alonge', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/37c6', 9, 'STUDENT', 'Victor', 'Ezekiel', 'Mr Ezekiel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/64ed', 9, 'STUDENT', 'Lekan', 'Anthony', 'Anthony', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/163d', 9, 'STUDENT', 'Mercy', 'Ayodele', 'Mr Ayodele', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/a517', 9, 'STUDENT', 'Esther', 'Samaila', 'Sumaila', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/b85a', 9, 'STUDENT', 'Anjola', 'Fatunmbi', 'Fatumbi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/8723', 9, 'STUDENT', 'Samuel', 'Uti', 'Mr Uti', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/582f', 9, 'STUDENT', 'Shola', 'Folorunsho', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/e010', 9, 'STUDENT', 'Ramadan', 'Kewulere', 'Kewulere', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/63c8', 9, 'STUDENT', 'Halimat Amira', 'Hussein', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/265f', 9, 'STUDENT', 'Nanafirdausi', 'Abdulahi', 'Mr Abdyllai', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/23b1', 9, 'STUDENT', 'Ademola', 'Raji', 'Raji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/8f50', 9, 'STUDENT', 'Abdulahi', 'Yusuf', 'Yusuf', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/58e6', 9, 'STUDENT', 'Abideen', 'Lawal', 'Mr lawal', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/67f0', 9, 'STUDENT', 'Abdulaziz', 'Mohamed', 'Mr Mohammed', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/890d', 9, 'STUDENT', 'Success', 'Ogbona', 'Mr ogbonna', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/62f2', 9, 'STUDENT', 'Rafiat Omowumi', 'Aliu', 'Mr aliu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/c9de', 9, 'STUDENT', 'Opeyemi', 'Ayedu', 'Mr Ayedun', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/2a4a', 9, 'STUDENT', 'Solomon', 'Duru', 'Mr Solomon', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/ef48', 9, 'STUDENT', 'David', 'Owocho', 'Mr owoicho', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/af45', 9, 'STUDENT', 'Destiny', 'Nwokono', 'Mr Nwokono', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3735', 9, 'STUDENT', 'Yetunde', 'Fatunmbi', 'Mr Fatunmbi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/c12e', 9, 'STUDENT', 'Abigail kanyinsola', 'Oluwadare', 'Mr Oluwadare', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3bf6', 9, 'STUDENT', 'Opeyemi', 'Alabi', 'Mr Alabi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/6180', 9, 'STUDENT', 'Rhoda', 'Uwondo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/51c3', 9, 'STUDENT', 'Gloria', 'Iriah', 'Mr Iriah', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/2f91', 9, 'STUDENT', 'Desola', 'Akinrinola', 'Mr Akinrinola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/7106', 9, 'STUDENT', 'Rachel', 'Francis', 'Mr Francis', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/21c5', 9, 'STUDENT', 'Abdulahi', 'Abubakar', 'Mr Abdullahi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/6568', 9, 'STUDENT', 'Temitope', 'Adebayo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/f2a9', 9, 'STUDENT', 'Feranmi', 'Olusoji', 'Mr Olusoji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/5fa7', 9, 'STUDENT', 'Khalid', 'Yusuf', 'Mr Yusuf', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/475d', 9, 'STUDENT', 'Alfred', 'Obaro', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1dd3', 9, 'STUDENT', 'Fuad', 'Oyegunle', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/84de', 9, 'STUDENT', 'Ayomide', 'Badmus', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/32e0', 9, 'STUDENT', 'Adebukola', 'Adesina', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/cd14', 9, 'STUDENT', 'Boluwatife', 'Oyewusi', 'Mr Rotimi Oyewusi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/049a', 9, 'STUDENT', 'Fareedah', 'Okunlade', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/8b06', 9, 'STUDENT', 'Feelah', 'Stanley', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/8c23', 9, 'STUDENT', 'Chidima Jenifer', 'Okoli', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/fecb', 9, 'STUDENT', 'Oluwajimi', 'Adeniyi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/6333', 9, 'STUDENT', 'Richmond', 'Uduimoh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/c1f3', 9, 'STUDENT', 'Daniel', 'James', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/7d2c', 9, 'STUDENT', 'Godspower', 'Nsofor', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/daf7', 9, 'STUDENT', 'Anthony', 'Ochechi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/de77', 9, 'STUDENT', 'Justina', 'Nsima', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/95b9', 9, 'STUDENT', 'Ama-oyindamola', 'George', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/73e0', 9, 'STUDENT', 'Rachel', 'Uduimoh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/d86a', 9, 'STUDENT', 'Fatima', 'Yusuf', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/be9b', 9, 'STUDENT', 'Wisdom', 'Cletus', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/24c0', 9, 'STUDENT', 'Aishat', 'Yusha\u, , , image.png, image.png, balkisuibrahim@gmail.com, 08077316160, Finished, NULL, , , , , , ', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/cf87', 9, 'STUDENT', 'Cliton', 'Omojola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/589f', 9, 'STUDENT', 'Tochuku', 'Thadeus', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/8117', 9, 'STUDENT', 'Micheal', 'Olajide', 'Olajide', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/e822', 9, 'STUDENT', 'Mustapha', 'Abubakar', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/f1fc', 9, 'STUDENT', 'Kelvin', 'Okhai', 'Mr okhai', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/21a3', 9, 'STUDENT', 'Jessica', 'Uwadiale', 'Mr Uwadiale', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/de48', 9, 'STUDENT', 'Shamsiyya', 'Usman', 'Usman Gali', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/f5b2', 9, 'STUDENT', 'Olusoji Feranmi', 'David', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/760c', 9, 'STUDENT', 'Opeyemi', 'Ayeni', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/5efa', 9, 'STUDENT', 'Sylvester', 'Adah', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/ecfc', 9, 'STUDENT', 'Olayinka Sofiyah', 'Sanni', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/a469', 9, 'STUDENT', 'Oyindamola Bolaji', 'Olowookere', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/fb63', 9, 'STUDENT', 'Martins Chibueze', 'Anyiam', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/336c', 9, 'STUDENT', 'Favour', 'Imahia', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/9922', 9, 'STUDENT', 'Hunaidatu', 'Muazu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/6851', 9, 'STUDENT', 'Inioluwa', 'Awotunde', 'Mr Tosin Awotunde', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1dee', 9, 'STUDENT', 'Godwin', 'Ibe', 'Joeachim maduchem', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/48b2', 9, 'STUDENT', 'Lawrence', 'Patrick', 'Patrick', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3865', 9, 'STUDENT', 'Marvellous', 'Akinola', 'Akinola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/512d', 9, 'STUDENT', 'Boluwatife Moropedaoluwa', 'Johnny', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/1314', 9, 'STUDENT', 'Deborah Oghenemrore', 'Edijala', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/e447', 9, 'STUDENT', 'Micheal', 'Kayode', 'Mr Kayode', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3ed0', 9, 'STUDENT', 'Jushua', 'Okeke', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/00eb', 9, 'STUDENT', 'Ademola', 'Adetayo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/f12f', 9, 'STUDENT', 'Jerry', 'Jwangwa', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/cbda', 9, 'STUDENT', 'Taiwo', 'Omoloja', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/4366', 9, 'STUDENT', 'Opeyemi', 'Saheed', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/04d3', 9, 'STUDENT', 'Pius', 'Iyobhebhe', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/3e0c', 9, 'STUDENT', 'Ifeanyi Emmanuel', 'Emebene', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/c7e2', 9, 'STUDENT', 'Daniel', 'Uti', 'Uti', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/42dd', 9, 'STUDENT', 'Faranpojo', 'David', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/0afb', 9, 'STUDENT', 'Divine', 'Bekeh', 'Mr Bekeh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/f726', 9, 'STUDENT', 'Serah', 'Salihu', 'Mr salihu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/8c69', 9, 'STUDENT', 'Favour', 'Mbikpo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2022/78ce', 9, 'STUDENT', 'Test', 'Test', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/4426', 9, 'STUDENT', 'Amirat', 'Abdulwahab', 'Mr Abdulwahab', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/ddcc', 9, 'STUDENT', 'Albert', 'Obaro', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/b000', 9, 'STUDENT', 'Sofiat', 'Shuttu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/5f7a', 9, 'STUDENT', 'Lilian', 'Amasetimin', 'Mr Amasitimin', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/9379', 9, 'STUDENT', 'Malmoud', 'Adamu', 'Mr Adamu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/833e', 9, 'STUDENT', 'Favour', 'Okolie', 'Mr Okolie', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/735f', 9, 'STUDENT', 'Fredrick', 'Etop', 'Etop', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/ac78', 9, 'STUDENT', 'Haliat', 'Idowu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/86bc', 9, 'STUDENT', 'Sheidu', 'Emmanuel', 'Sheidu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/50bf', 9, 'STUDENT', 'Rukayat', 'Adamu', 'Adamu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/ed04', 9, 'STUDENT', 'Joseph', 'Ndunche', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/0eb7', 9, 'STUDENT', 'Obera Emmanuel', 'Emmanuel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/02ef', 9, 'STUDENT', 'Blessing', 'Samuel', 'Samuel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/5a35', 9, 'STUDENT', 'Precious', 'Osas', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/2586', 9, 'STUDENT', 'Ajibola Sultol', 'Ibrahim', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/ef63', 9, 'STUDENT', 'Favour', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/f1a0', 9, 'STUDENT', 'Boluwatife', 'Oladimeji', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/7d96', 9, 'STUDENT', 'Adeworan', 'Adeola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/7ab5', 9, 'STUDENT', 'Ruth Oyindamola', 'Ogunjobi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/81ca', 9, 'STUDENT', 'Ruth Oyindamola', 'Ogunjobi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/6201', 9, 'STUDENT', 'Dominica', 'Anyanwa', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/d325', 9, 'STUDENT', 'Elizabeth', 'Ezekiel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/a2d9', 9, 'STUDENT', 'Elizabeth', 'Ezekiel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/ecdb', 9, 'STUDENT', 'Adiza', 'Bello', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/38c6', 9, 'STUDENT', 'Abdulahi', 'Suliman', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/119a', 9, 'STUDENT', 'Muhammed  Awan', 'Hussein', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/fad5', 9, 'STUDENT', 'Grace', 'Iziokhi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/fe62', 9, 'STUDENT', 'David', 'Richmond', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/dd3f', 9, 'STUDENT', 'Destiny', 'Ipere', 'Paul ipere', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/b08c', 9, 'STUDENT', 'Bright', 'Daniela', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/78ad', 9, 'STUDENT', 'Praise', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/f17f', 9, 'STUDENT', 'Ochechi', 'Rose', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/cfdd', 9, 'STUDENT', 'Precious', 'Omeje', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/1037', 9, 'STUDENT', 'Fiyinfoluwa', 'Sahley', 'Mr Sahley', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/c974', 9, 'STUDENT', 'Favour', 'Mobolaji', 'Mr Mobolaji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/4e74', 9, 'STUDENT', 'Mfoniso', 'Otobong', 'Mr Asukwo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/3e7c', 9, 'STUDENT', 'Joshua  Ayomide', 'Ogunjobi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/b343', 9, 'STUDENT', 'Ruth', 'Ogunjobi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/a551', 9, 'STUDENT', 'Destiny', 'Ipere', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/ff90', 9, 'STUDENT', 'Richmond', 'David', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/52a1', 9, 'STUDENT', 'Murayo', 'Micheal', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/d808', 9, 'STUDENT', 'Precious', 'Omeje', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/4b53', 9, 'STUDENT', 'Adeola', 'Adeworan', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/880b', 9, 'STUDENT', 'Muhammed', 'Hussein', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/3883', 9, 'STUDENT', 'Ajibola', 'Ibrahim', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/c303', 9, 'STUDENT', 'Praise', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/a46f', 9, 'STUDENT', 'Daniella', 'Bright', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/4ecc', 9, 'STUDENT', 'Hadizah', 'Bello', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/d59a', 9, 'STUDENT', 'Elizabeth', 'Ezekiel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/7b79', 9, 'STUDENT', 'Favour', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/fb57', 9, 'STUDENT', 'Suliman', 'Abdullahi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/a54e', 9, 'STUDENT', 'Grace', 'Iziokhai', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/936e', 9, 'STUDENT', 'Roseline', 'Ochechi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/8f9d', 9, 'STUDENT', 'Boluwatife', 'Oladimeji', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/6ca2', 9, 'STUDENT', 'Daniella', 'Anyanwu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/8bb8', 9, 'STUDENT', 'Mercy', 'Olabiyi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/1f48', 9, 'STUDENT', 'Omotola', 'Balogun', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/db41', 9, 'STUDENT', 'Usman', 'Yusuf', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/cc05', 9, 'STUDENT', 'Aliyah', 'Bello', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/c453', 9, 'STUDENT', 'Oyindamola', 'Akinsola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/7014', 9, 'STUDENT', 'Aishat', 'Abdulrasak', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/d777', 9, 'STUDENT', 'Gift', 'Chukwu', 'Mr Chukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/3607', 9, 'STUDENT', 'Emmanuel', 'Obera', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/dec8', 9, 'STUDENT', 'Anabell chikezie', 'Kelechi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/adc9', 9, 'STUDENT', 'Precious', 'Osas', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/6721', 9, 'STUDENT', 'James', 'Ugbeh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2023/198e', 9, 'STUDENT', 'John', 'Ugebeh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/abde', 9, 'STUDENT', 'Goodness  Odion', 'Odion', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/f33e', 9, 'STUDENT', 'Mercy Akhere', 'Odion', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/509d', 9, 'STUDENT', 'Olabosipo', 'Akinleye', 'Mr Akinleye', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/e2f1', 9, 'STUDENT', 'Goodness', 'Emmanuel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/4085', 9, 'STUDENT', 'Blessing', 'Nkwocha', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/b34e', 9, 'STUDENT', 'Monsurat Opeoluwa', 'Oyedepo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/b4cd', 9, 'STUDENT', 'Christabel', 'Iyoha', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('student/2024/34d4', 9, 'STUDENT', 'Melissa', 'Ogherena', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/cc2e', 9, 'STUDENT', 'Akinnifesi', 'Clara', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/e52e', 9, 'STUDENT', 'Gift', 'Chukwu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/e560', 9, 'STUDENT', 'Quadri', 'Adeyanju', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/16ac', 9, 'STUDENT', 'Ayodele', 'Goodness', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/2a63', 9, 'STUDENT', 'Elizabeth', 'Iwelunmo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/e227', 9, 'STUDENT', 'David', 'Akinola', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/9cc5', 9, 'STUDENT', 'Victory', 'Iriah', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/492d', 9, 'STUDENT', 'Gideon', 'Bisiriyu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/2b9a', 9, 'STUDENT', 'Nifemi', 'Olajide', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/0644', 9, 'STUDENT', 'Success', 'Oghene', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/6c9b', 9, 'STUDENT', 'Divine', 'Labija', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/912d', 9, 'STUDENT', 'Destiny', 'Mbkpo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/0e74', 9, 'STUDENT', 'Obehi Gift', 'Ogunleye', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/e4cc', 9, 'STUDENT', 'Imran', 'Bilal', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/a285', 9, 'STUDENT', 'Divine Faour', 'Adewale', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/16fd', 9, 'STUDENT', 'Emmanuella', 'Oluya', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/850f', 9, 'STUDENT', 'Owen', 'Richard Ebenezer', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/5ed2', 9, 'STUDENT', 'Godspower', 'Oluwole', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/7cc1', 9, 'STUDENT', 'Gold', 'Akinyode', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/6889', 9, 'STUDENT', 'Nifemi', 'Adebowale', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/cf4a', 9, 'STUDENT', 'Yasirah', 'Lawal Isa', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/f6e4', 9, 'STUDENT', 'Precious', 'Isaac', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/b6a8', 9, 'STUDENT', 'Ben', 'Clinton', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/f99c', 9, 'STUDENT', 'Ben', 'Victor', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/721d', 9, 'STUDENT', 'Olohimai Michelle', 'Philip', 'Philip Eguaomon Uanserume', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/f0f3', 9, 'STUDENT', 'Amidat', 'Fadare', 'Mr Fadare', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/e854', 9, 'STUDENT', 'Elizabeth', 'Oluya', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/ee4e', 9, 'STUDENT', 'Emmanuel', 'Patrick', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/ef24', 9, 'STUDENT', 'Prospect', 'Chiabuotu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/ba60', 9, 'STUDENT', 'Caleb', 'Adekonya', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/0f81', 9, 'STUDENT', 'Chikamso Stanley', 'Umunna', 'Umunna Innocent Chukwuemeka', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/64c1', 9, 'STUDENT', 'Alex', 'Anthony', 'Anthony Musa', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/b311', 9, 'STUDENT', 'Khalid', 'Ismail', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/b29a', 9, 'STUDENT', 'Lifted', 'James Praise', 'Mr James Praise', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/960d', 9, 'STUDENT', 'Taiwo marvellous', 'Ajaye', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/5189', 9, 'STUDENT', 'Kehinde mercy', 'Ajayi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/ae18', 9, 'STUDENT', 'Enoch Ohizimede', 'Oluya', 'OLUYA GREGORY OGBETA', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/1ed8', 9, 'STUDENT', 'Peace Chiwendu', 'Eze', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/ac01', 9, 'STUDENT', 'Oseremhen', 'Iyere', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/425c', 9, 'STUDENT', 'Precious', 'Philip', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/9b71', 9, 'STUDENT', 'Sultan Timilehin', 'Ismail', 'Ismail Ibrahim', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/cbc9', 9, 'STUDENT', 'Ize Fridaus', 'Muhammad', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/5cd4', 9, 'STUDENT', 'Victor Oluwaseun', 'Akinnifesi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/6395', 9, 'STUDENT', 'Testimony', 'Iriah', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/cd24', 9, 'STUDENT', 'Aliyat', 'Idowu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/229c', 9, 'STUDENT', 'Patrick', 'Emmanuel', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/14ef', 9, 'STUDENT', 'Samuel', 'Omeje', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2024/2d9a', 9, 'STUDENT', 'Sultan', 'Ismail', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/0669', 9, 'STUDENT', 'Ibukun', 'Akinyemi', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/9d71', 9, 'STUDENT', 'ONUH', 'PRECIOUS', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/b8f5', 9, 'STUDENT', 'Immaculate', 'Nwabudike', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/f2e9', 9, 'STUDENT', 'Awwal', 'Lawal', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/822e', 9, 'STUDENT', 'Fareedah', 'Jimoh', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/dc58', 9, 'STUDENT', 'Victory', 'Adewale', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/4148', 9, 'STUDENT', 'Monica', 'Agwo', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/9b1a', 9, 'STUDENT', 'Elijah', 'Benjamin', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/ce09', 9, 'STUDENT', 'Goodluck', 'Ikor', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/a339', 9, 'STUDENT', 'vanessa', 'Isong', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/277f', 9, 'STUDENT', 'Ayoritse', 'Atafiri', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/f166', 9, 'STUDENT', 'Success', 'Olom', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/0a9f', 9, 'STUDENT', 'ISAAC', 'DIVINE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/5187', 9, 'STUDENT', 'Godwin', 'Oluwole', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/949f', 9, 'STUDENT', 'ISAAC', 'ANTHONY', 'Anthony Musa', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/d612', 9, 'STUDENT', 'DAVID', 'OTEGBAYO', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/e0c9', 9, 'STUDENT', 'JOEL', 'CHRISTIAN', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/0310', 9, 'STUDENT', 'VICTORY', 'AKAOGWU', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/6396', 9, 'STUDENT', 'SEKEMI', 'ORISAWUYI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/3eb6', 9, 'STUDENT', 'IFEOLUWA', 'AKINYEMI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/16fe', 9, 'STUDENT', 'ANNABEL', 'IYOHA', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/7d20', 9, 'STUDENT', 'JOY', 'DURU', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/cfc2', 9, 'STUDENT', 'ANIBIJUWON', 'ELIZABETH', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/25d3', 9, 'STUDENT', 'DOMINION', 'ENAKAHIRE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/e081', 9, 'STUDENT', 'FARUQ', 'ADIGUN FADERE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/ace9', 9, 'STUDENT', 'MASARAT', 'IBUOWO', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/bab7', 9, 'STUDENT', 'KING DAVID', 'AKINJO', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/beb0', 9, 'STUDENT', 'HALEEMAT', 'AMEED', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/c58a', 9, 'STUDENT', 'ZAMAT', 'LAWAL', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/7702', 9, 'STUDENT', 'KAMSI', 'NZEWI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/ebe4', 9, 'STUDENT', 'FAVOUR', 'NWABUDIKE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/6d99', 9, 'STUDENT', 'JESSICA', 'UGBEH', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/0538', 9, 'STUDENT', 'Mariam', 'Adamu', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/5382', 9, 'STUDENT', 'PEACE', 'INNOCENT', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/1c37', 9, 'STUDENT', 'AMIDAT', 'ADIGUN FADERE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/022f', 9, 'STUDENT', 'Unknown', '', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/c5b8', 9, 'STUDENT', 'Unknown', '', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/d23d', 9, 'STUDENT', 'Unknown', '', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/cbdb', 9, 'STUDENT', 'DISU', 'AL\AMEEN, , , image.png, , auspom4real@gmail.com, 08062093770, SS2A, Male, , , , , , $2y$10$bP01QU7L', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/6732', 9, 'STUDENT', 'SULAINMAN', 'BARAKAT', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/e63b', 9, 'STUDENT', 'CRISTIANO', 'IDEMUDIA', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/9ec1', 9, 'STUDENT', 'CRISTIANO', 'IDEMUDIA', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/8ec8', 9, 'STUDENT', 'OLUWAFERANMI', 'OLAJIDE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/1c47', 9, 'STUDENT', 'ONUH', 'PRECIOUS', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/6752', 9, 'STUDENT', 'SAMUEL', 'OMENJE', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/ff09', 9, 'STUDENT', 'IBUKUNOLUWA', 'AKINYEMI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/ed86', 9, 'STUDENT', 'PROMISE', 'TAIWO', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2025/1522', 9, 'STUDENT', 'OLOHIMAI MICHELLE', 'PHILIP', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2026/e6a9', 9, 'STUDENT', 'Suliamon', 'Qosim', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2026/1cd7', 9, 'STUDENT', 'GRACE', 'AFOLABI', 'Unknown', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/83d0', 8, 'STUDENT', 'Miracle', 'O.', 'Ofoegbu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4f1d', 8, 'STUDENT', 'Adakole', '', 'Olivia', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/bb0e', 8, 'STUDENT', 'Praise', 'Darasimi', 'Akinbola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/a5e6', 8, 'STUDENT', 'Akinlabi', '', 'Aisha', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4b9b', 8, 'STUDENT', 'Adakole', '', 'Great', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d686', 8, 'STUDENT', 'Emenike', '', 'Destiny', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/b4f1', 8, 'STUDENT', 'Chukwuka', '', 'Brian', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4405', 8, 'STUDENT', 'Tomiwa', '', 'Ajayi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/1f47', 8, 'STUDENT', 'Kogberegbe', '', 'Oyindamola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/37bf', 8, 'STUDENT', 'Ronaldo', '', 'Anaelechukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/bd2b', 8, 'STUDENT', 'Anjorin', '', 'Emmanuel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/23f4', 8, 'STUDENT', 'Bamisaye', '', 'Praise', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/c775', 8, 'STUDENT', 'Balogun', '', 'Abubakar-sidiq', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/3de0', 8, 'STUDENT', 'Yakub', '', 'Alia', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/92d4', 8, 'STUDENT', 'Divine', '', 'Osuji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/ebcb', 8, 'STUDENT', 'Shokoya', '', 'Emmanuel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/72c2', 8, 'STUDENT', 'Royhan', '', 'Abdulrasaq', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/816f', 8, 'STUDENT', 'Elemide', '', 'Christabel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/ac60', 8, 'STUDENT', 'Kamara', '', 'Onyema', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/bef6', 8, 'STUDENT', 'Abe', '', 'Dominic', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d5dc', 8, 'STUDENT', 'Hephzibah', 'Oluwanifemi', 'Oladimeji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4a99', 8, 'STUDENT', 'David', '', 'Awele', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/f063', 8, 'STUDENT', 'Adetola', '', 'Adedeji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/6aae', 8, 'STUDENT', 'Destiny', '', 'Osuji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/53fe', 8, 'STUDENT', 'Olumide', '', 'Emmanuella', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/0af2', 8, 'STUDENT', 'Dolapo', '', 'Balogun', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/0b25', 8, 'STUDENT', 'Joseph', '', 'Chinecherem', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/c72a', 8, 'STUDENT', 'Chijioke', '', 'Chisom', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/0b00', 8, 'STUDENT', 'Mfoniso', '', 'Emmanuel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d161', 8, 'STUDENT', 'Emmanuel', '', 'Christian', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/8172', 8, 'STUDENT', 'Confidence', '', 'Blessing', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/50fe', 8, 'STUDENT', 'Monalisa', '', 'Duru', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/78e9', 8, 'STUDENT', 'Usen Ekpo', '', 'Joseph', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/0abf', 8, 'STUDENT', 'Abdulmalik', '', 'Ayeloja', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/692d', 8, 'STUDENT', 'Anelechukwu', '', 'Juanita', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4637', 8, 'STUDENT', 'Josephine', '', 'Oluwatuyi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/a4bf', 8, 'STUDENT', 'Ayodele', '', 'Goodness', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/e9ab', 8, 'STUDENT', 'Anabel', '', 'Ubanwa', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/ff4b', 8, 'STUDENT', 'Kanyinsola', 'Lateefah', 'Sedun', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/de0e', 8, 'STUDENT', 'David', '', 'Shaun', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/99ef', 8, 'STUDENT', 'Gabriel', 'Olamilekan', 'Joseph', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/c954', 8, 'STUDENT', 'David', '', 'Anifowoshe', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/bfce', 8, 'STUDENT', 'Emmanuel', '', 'Igboanusi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/f17d', 8, 'STUDENT', 'Ayomide', '', 'Odushina', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/e8d5', 8, 'STUDENT', 'Precious', 'Sinaayomi', 'Olukayode', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d2e2', 8, 'STUDENT', 'Darasimi', '', 'Omotoso', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/8d96', 8, 'STUDENT', 'Micheal', 'Boluwatife', 'Joseph', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/5429', 8, 'STUDENT', 'Samuel', '', 'Charles', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4743', 8, 'STUDENT', 'Praise', 'Favor', 'Oladimeji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/027f', 8, 'STUDENT', 'David', 'Chukwunonso', 'Emmanuel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/a2ed', 8, 'STUDENT', 'Blessing', '', 'Ejeh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/1a6d', 8, 'STUDENT', 'Melissa', 'Miracle', 'Ighodaro', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/6ee1', 8, 'STUDENT', 'Anita', '', 'Udobassey', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4be6', 8, 'STUDENT', 'Gloria', '', 'Ugochukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/b0e6', 8, 'STUDENT', 'Jarib', '', 'Eze', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d592', 8, 'STUDENT', 'Qozeem', '', 'Atoba', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/e104', 8, 'STUDENT', 'Roselyn', '', 'Okiri', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/e6d9', 8, 'STUDENT', 'Delight', '', 'Emeka', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/6fc6', 8, 'STUDENT', 'Shefiq', '', 'Abdulrasaq', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/7f4b', 8, 'STUDENT', 'Sterling', '', 'David', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/30a3', 8, 'STUDENT', 'Kikiope', '', 'Olayiwola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/ee14', 8, 'STUDENT', 'Anthony', '', 'Olufemi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/90f0', 8, 'STUDENT', 'Fortune', '', 'Obanwa', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/3d8b', 8, 'STUDENT', 'Praise', '', 'Aaron', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/45eb', 8, 'STUDENT', 'Moses', '', 'Bliss', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/1b61', 8, 'STUDENT', 'Iniola', '', 'Dada', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/a53f', 8, 'STUDENT', 'Momoh', '', 'Michelle', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/ecd7', 8, 'STUDENT', 'Analaba', '', 'Chioma', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/6c05', 8, 'STUDENT', 'Williams', '', 'Domeih', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/8f8b', 8, 'STUDENT', 'Adewale', '', 'Rihanat', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/dec1', 8, 'STUDENT', 'Solomon', '', 'Nwodo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/b15e', 8, 'STUDENT', 'David', '', 'Maurice', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/e82f', 8, 'STUDENT', 'Isaac', '', 'Arinze', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/07e1', 8, 'STUDENT', 'Enoch', '', 'Olumide', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/a143', 8, 'STUDENT', 'Tobi', '', 'Ojo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/dd25', 8, 'STUDENT', 'Joshua', '', 'Olushola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/f750', 8, 'STUDENT', 'Zuriel', '', 'Adegbile', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d642', 8, 'STUDENT', 'Chidera', '', 'Onyemelukwe', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/7ce5', 8, 'STUDENT', 'Denning', '', 'Ubanwa', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/e9fd', 8, 'STUDENT', 'Chukwujekwu', '', 'Obi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/cafb', 8, 'STUDENT', 'Pemisire', '', 'Adeoye', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/c286', 8, 'STUDENT', 'Chidera', '', 'Chukwuma', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/8e08', 8, 'STUDENT', 'Adenike', '', 'Adewole', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4795', 8, 'STUDENT', 'Chisimdi', '', 'Uzochukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/00f1', 8, 'STUDENT', 'Olamide', '', 'Adewale', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/db1a', 8, 'STUDENT', 'Racheal', '', 'Oyedeji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/c0e0', 8, 'STUDENT', 'Anifowoshe Elizabeth', '', 'Olorunfemi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/96d9', 8, 'STUDENT', 'Ethan', '', 'Eteriebe', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/73e8', 8, 'STUDENT', 'Eneh', '', 'Benedict', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/5188', 8, 'STUDENT', 'Pamilerin', '', 'Omotolani', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/9bd2', 8, 'STUDENT', 'Anjolaoluwa', '', 'Omowaye', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d139', 8, 'STUDENT', 'Annabel', '', 'Oni', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/9c3d', 8, 'STUDENT', 'Deborah', '', 'Osadion', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/58ff', 8, 'STUDENT', 'Quamdeen', '', 'Abdulrasaq', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/3f6d', 8, 'STUDENT', 'Nancy', '', 'Jones', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/5e97', 8, 'STUDENT', 'Emmanuel', '', 'Shokoya', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d4c8', 8, 'STUDENT', 'Oyindamola', '', 'Kogberegbe', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/f9ac', 8, 'STUDENT', 'OLATUBOSUN', '', 'IJALANA', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/135e', 8, 'STUDENT', 'Emmanuel', '', 'Abajingin', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/9ca8', 8, 'STUDENT', 'Alexander', '', 'Adefemi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/0e02', 8, 'STUDENT', 'Al-Ameen', '', 'Adejumo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/3a34', 8, 'STUDENT', 'Arnold', '', 'Anaelechukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/af14', 8, 'STUDENT', 'Olatomiwa', '', 'Ayodeji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/b421', 8, 'STUDENT', 'Adebayo', '', 'Balogun', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/32a6', 8, 'STUDENT', 'Samuel', '', 'Jones', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/baac', 8, 'STUDENT', 'Ifechukwu', '', 'Chieme-anozie', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/33b9', 8, 'STUDENT', 'Joel', '', 'Domeih', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/6aa3', 8, 'STUDENT', 'Somto', '', 'Ekeh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/0c00', 8, 'STUDENT', 'Favour', '', 'Godwin', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/4c19', 8, 'STUDENT', 'Obinna', '', 'Nwankwo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/a6e7', 8, 'STUDENT', 'David', '', 'Oliver', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/3917', 8, 'STUDENT', 'Samuel Ayomikun Kelechi', '', 'Onyema', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/247d', 8, 'STUDENT', 'Samuel', '', 'Osuji', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d3cf', 8, 'STUDENT', 'Daniel', '', 'Paul', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d4e7', 8, 'STUDENT', 'Faruk', '', 'Taiwo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/b5c1', 8, 'STUDENT', 'Fiwajojesu', '', 'Adeoye', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/dd62', 8, 'STUDENT', 'Jessica', '', 'Aisiku', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/ab82', 8, 'STUDENT', 'Precious', '', 'Bamisaye', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/2610', 8, 'STUDENT', 'Angel', '', 'Nwaigbo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/8bc9', 8, 'STUDENT', 'Tobiloba', '', 'Ojo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/9db5', 8, 'STUDENT', 'Oluwafisayomi', '', 'Olajide', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/611d', 8, 'STUDENT', 'Folafunmi', '', 'Olupalace', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/b041', 8, 'STUDENT', 'Inioluwa', '', 'Omotoso', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/7d69', 8, 'STUDENT', 'Deborah', '', 'Owolabi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/e12b', 8, 'STUDENT', 'Ngozi', '', 'Ozoemena', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/33dd', 8, 'STUDENT', 'Penuel', '', 'Temilade', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/b7ca', 8, 'STUDENT', 'Araoluwa', '', 'Olupalace', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/612f', 8, 'STUDENT', 'Oselumen', '', 'Inetabor', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/ff3f', 8, 'STUDENT', 'Jeffrey', 'Ugonna', 'Ukachukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/eced', 8, 'STUDENT', 'Kehinde', '', 'Oshikoya', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/c791', 8, 'STUDENT', 'Taiwo', '', 'Oshikoya', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/d07d', 8, 'STUDENT', 'God\streasure, , Ogunnaike, Ogunnaike Opeoluwa, Ogunnaike Ruth, 1733838010.jpeg, image.png, ogunnaik', 'brave', 'bold and confident. I am a good team player., 2024, $2y$10$pqFlK9kAMyfmbvYa2NM0M.82rL8M4rlHSgMmVoamt', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/26a3', 8, 'STUDENT', 'Daniel', '', 'Oliver', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/60eb', 8, 'STUDENT', 'Aliya', 'Abiodun', 'Kajola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2024/273a', 8, 'STUDENT', 'Ivan', '', 'Ossai', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/c63d', 8, 'STUDENT', 'Jerahmeel', '', 'Ezeh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/e5e8', 8, 'STUDENT', 'Tunmise', '', 'Olusuyi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/cbab', 8, 'STUDENT', 'Pemisire', '', 'Oyedele', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/4ff1', 8, 'STUDENT', 'William', '', 'Domeih', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/1fab', 8, 'STUDENT', 'Joel', '', 'Domeih', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/abf7', 8, 'STUDENT', 'Joel', '', 'Domeih', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/84ff', 8, 'STUDENT', 'Azeemah Ayotomiwa', '', 'Oke', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/aff3', 8, 'STUDENT', 'Abundance Ozioma', '', 'Ugochukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/89ae', 8, 'STUDENT', 'David', '', 'Anike', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/0a53', 8, 'STUDENT', 'Praise Iremide', '', 'Mayaki', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/a323', 8, 'STUDENT', 'Precious Chioma', '', 'Obinna', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/ec77', 8, 'STUDENT', 'Abiola Mary', '', 'Omotola', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/83a5', 8, 'STUDENT', 'Esther Feranmi', '', 'Orelaru', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/1cd0', 8, 'STUDENT', 'Kamsiyochukwu Annastatia', '', 'Onovo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/8929', 8, 'STUDENT', 'Akeelah Ewawunmi', '', 'Oke', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/355b', 8, 'STUDENT', 'Michael Chinecherem', '', 'Chukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/6137', 8, 'STUDENT', 'Sam-Elijah Oluwapamilerin', '', 'Dan-Akoja', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/562d', 8, 'STUDENT', 'Temilorun Andrew', '', 'Showemimo', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/cb37', 8, 'STUDENT', 'Favour Oluomachi', '', 'Odimba', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/4451', 8, 'STUDENT', 'Peter Chidumebi', '', 'Ugochukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/38e2', 8, 'STUDENT', 'Rihanat Oyindamola', '', 'Badmus', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/4e4d', 8, 'STUDENT', 'Cecilia Onyedikachukwu', '', 'Amuta', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/3787', 8, 'STUDENT', 'Great Chinedu', '', 'Confidence', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/2d37', 8, 'STUDENT', 'Esther Ibukunoluwa', '', 'Kolawole', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/ced6', 8, 'STUDENT', 'Gabriel Chibike', '', 'Chukwuma', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/df35', 8, 'STUDENT', 'Purity Nifemi', '', 'Afolabi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/f91b', 8, 'STUDENT', 'Anointed Boluwatife', '', 'Oloja', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/133c', 8, 'STUDENT', 'Rosemary Chinaza', '', 'Okoh', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/392b', 8, 'STUDENT', 'David Osareti', '', 'Osadion', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/8ae0', 8, 'STUDENT', 'Esther Chiamaka', '', 'Sunday', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/44e9', 8, 'STUDENT', 'Daniella Chisom', '', 'Emmanuel', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/87db', 8, 'STUDENT', 'Claudia Chimumeremumma', '', 'Nnamdi', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/f3c5', 8, 'STUDENT', 'Immaculeta Oluchukwu', '', 'Nnacho', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/cd4a', 8, 'STUDENT', 'Evangelist Oluebube', '', 'Vitalis', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/a51d', 8, 'STUDENT', 'Faruq', '', 'Aminu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('fpis/2025/0dc1', 8, 'STUDENT', 'Paul', '', 'Ugochukwu', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2026/73eb', 8, 'STUDENT', 'Qozeem Babatunde', '', 'Atoba', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE'),
('greatkings/2026/2913', 8, 'STUDENT', 'Tolulope', '', 'Olalere', '$2a$12$1FIJWpe8kDVwGmygHntDWOhk7vNQnClUrTXUjGsLudXAOvFnJ1Iau', 'ACTIVE');
