ALTER TABLE `School`
  ADD COLUMN `slogan` VARCHAR(255) NULL,
  ADD COLUMN `motto` VARCHAR(255) NULL,
  ADD COLUMN `description` TEXT NULL,
  ADD COLUMN `contactEmail` VARCHAR(255) NULL,
  ADD COLUMN `contactName` VARCHAR(150) NULL,
  ADD COLUMN `alternatePhone` VARCHAR(50) NULL,
  ADD COLUMN `city` VARCHAR(100) NULL,
  ADD COLUMN `state` VARCHAR(100) NULL,
  ADD COLUMN `country` VARCHAR(100) NULL DEFAULT 'Nigeria',
  ADD COLUMN `website` VARCHAR(255) NULL,
  ADD COLUMN `accentColor` VARCHAR(20) NOT NULL DEFAULT '#84cc16';
